"use client";

import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
type Translations = Record<Language, Record<string, string>>;
const translations: Translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.templates': 'Templates',
    'nav.certificates': 'Certificates',
    'nav.faq': 'FAQ',
    'nav.management': 'Management',
    'nav.explore': 'Explore',
    'nav.contact': 'Contact',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Log Out',
    'auth.admin': 'Admin',
    'auth.team': 'Team',
    'auth.public': 'Public',
    
    // Templates
    'templates.title': 'Templates',
    'templates.subtitle': 'Manage and create certificate templates',
    'templates.create': 'Create Template',
    'templates.preview': 'Preview',
    'templates.search': 'Search templates...',
    'templates.allCategories': 'All Categories',
    'templates.noTemplates': 'No templates found',
    'templates.createNew': 'Create New Template',
    'templates.loading': 'Loading Templates',
    'templates.loadingMessage': 'Please wait while we fetch your templates.',
    'templates.errorLoading': 'Error loading templates',
    'templates.tryAgain': 'Try Again',
    
    // Certificates
    'certificates.title': 'Certificates',
    'certificates.subtitle': 'Manage and track certificates',
    'certificates.create': 'Create Certificate',
    'certificates.certificateId': 'Certificate Number',
    'certificates.recipient': 'Recipient',
    'certificates.issuedDate': 'Issued Date',
    'certificates.expiryDate': 'Expiry Date',
    'certificates.actions': 'Actions',
    'certificates.search': 'Search certificates...',
    'certificates.noCertificates': 'No certificates found',
    'certificates.category': 'Category',
    'certificates.description': 'Description',
    'certificates.updateSuccess': 'Certificate updated successfully!',
    'certificates.updateFailed': 'Failed to update certificate',
    'certificates.deleteNoPermission': "You don't have permission to delete certificates",
    'certificates.deleteConfirm': 'Are you sure you want to delete certificate for "{name}"?\n\nCertificate Number: {number}\n\nThis action cannot be undone.',
    'certificates.deleteSuccess': 'Certificate for "{name}" deleted successfully!',
    'certificates.deleteFailed': 'Failed to delete certificate. Please try again.',
    'certificates.deleting': 'Deleting...',
    'certificates.loading': 'Loading certificates...',
    'certificates.loadingMessage': 'Please wait while we fetch your certificates.',
    'certificates.errorLoading': 'Error loading certificates',
    'certificates.tryAgain': 'Try Again',
    'certificates.filterByDate': 'Filter by date',
    'certificates.export': 'Export',
    'certificates.exportPdf': 'Export as PDF',
    'certificates.downloadPng': 'Download PNG',
    'certificates.sendEmail': 'Send via Email',
    'certificates.generateLink': 'Generate Certificate Link',
    'certificates.showing': 'Showing {start}-{end} of {total} certificates',
    'certificates.filteredFrom': '(filtered from {total})',
    'certificates.previous': 'Previous',
    'certificates.next': 'Next',
    'certificates.page': 'Page {current} of {total}',
    'certificates.noCertificatesMessage': 'Try adjusting your search criteria or create a new certificate.',
    'certificates.updateDetails': 'Update certificate details.',
    'certificates.selectCategory': 'Select category',
    'certificates.preview': 'Certificate Preview',
    'certificates.previewDescription': 'View certificate details and information',
    'certificates.certificateTitle': 'CERTIFICATE',
    'certificates.certifyText': 'This is to certify that',
    'certificates.completedText': 'has successfully completed the',
    'certificates.certificateNo': 'Certificate No:',
    'certificates.issueDate': 'Issue Date:',
    'certificates.fallbackPreview': 'This is a fallback preview. Configure template text layers for a fully customized certificate design.',
    'certificates.memberInfoNotAvailable': 'Member information not available',
    'certificates.loadMemberDetailsFailed': 'Failed to load member details',
    'certificates.generate': 'Generate',
    'certificates.viewCertificates': 'View Certificates',
    'certificates.saveSuccessWithScore': 'Certificate and Score saved successfully! Would you like to view all certificates?',
    'certificates.saveSuccess': 'Certificate saved successfully! Would you like to view all certificates?',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.preview': 'Preview',
    'common.loading': 'Loading...',
    'common.tryAgain': 'Try Again',
    
    // Footer
    'footer.multilingual': 'Multilingual Platform',
    'footer.phone': '+6281380935185',
    'footer.email': 'fahrirafa.rpl1@gmail.com',
    'footer.location': 'Malang',
    
    // Language
    'language.english': 'English',
    'language.indonesia': 'Indonesia',
    'language.switch': 'Switch Language',
    
    // Theme
    'theme.switch': 'Switch Theme',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    
    // Hero Section
    'hero.title': 'Search Certificate',
    'hero.searchButton': 'Search',
    'hero.searching': 'Searching...',
    'hero.certificatePreview': 'Certificate Preview',
    'hero.close': 'Close',
    'hero.recipient': 'Name',
    'hero.category': 'Category',
    'hero.template': 'Template',
    'hero.issued': 'Issued',
    'hero.expires': 'Expires',
    'hero.noPreviewImage': 'No preview image',
    'hero.certificate': 'certificate',
    'hero.certificates': 'certificates',
    'hero.viewFullImage': 'Click to view full image',
    'hero.export': 'Export',
    'hero.exportAsPDF': 'Export as PDF',
    'hero.downloadPNG': 'Download PNG',
    'hero.sendViaEmail': 'Send via Email',
    'hero.imageNotAvailable': 'Certificate image not available to export',
    'hero.pdfLibraryMissing': 'PDF library missing. Please install \'jspdf\' dependency.',
    'hero.pdfExported': 'PDF exported',
    'hero.pngDownloaded': 'PNG downloaded successfully',
    'hero.noPublicLink': 'Certificate does not have a public link ID',
    'hero.linkCopied': 'Public certificate link copied',
    'hero.linkGenerateFailed': 'Failed to generate certificate link',
    'hero.linkShareable': 'Link can be shared via WhatsApp, Email, or other platforms',
    'hero.imageNotAvailableShort': 'Certificate image not available',
    'hero.emailQueued': 'Email queued successfully! Preview opened in new tab',
    'hero.loadCategoriesFailed': 'Failed to load categories',
    'hero.generateLink': 'Generate Certificate Link',
    'hero.certificateImage': 'Certificate Image',
    'hero.sendEmailTitle': 'Send Certificate via Email',
    'hero.sendEmailSubtitle': 'Configure email details',
    'hero.certificatePreviewLabel': 'Certificate Preview:',
    'hero.recipientEmail': 'Recipient Email',
    'hero.subject': 'Subject',
    'hero.message': 'Message',
    'hero.emailSubjectPlaceholder': 'Email subject',
    'hero.emailMessagePlaceholder': 'Email message',
    'hero.cancel': 'Cancel',
    'hero.sendEmail': 'Send Email',
    'hero.sending': 'Sending...',
    'hero.emailSentSuccess': 'Email sent successfully to',
    'hero.emailValidationRequired': 'Recipient email is required',
    'hero.emailValidationInvalid': 'Please enter a valid email address',
    'hero.subjectRequired': 'Subject is required',
    'hero.messageRequired': 'Message is required',
    'hero.emailInvalidFields': 'Invalid email address or missing required fields',
    'hero.emailServiceUnavailable': 'Email service not available',
    'hero.emailServerError': 'Server error. Please try again later',
    'hero.emailSendFailed': 'Failed to send email. Please try again.',
    'hero.emailPrepareFailed': 'Failed to prepare email',
    'hero.exportPdfFailed': 'Failed to export PDF',
    'hero.exportPngFailed': 'Failed to export PNG',
    'hero.fetchImageFailed': 'Failed to fetch image',
    'hero.emailDefaultSubject': 'Certificate #{number}',
    'hero.emailDefaultSubjectNoNumber': 'Your Certificate',
    'hero.emailDefaultGreeting': 'Dear',
    'hero.emailDefaultInfo': 'Certificate Information:',
    'hero.emailDefaultCertNumber': 'Certificate Number',
    'hero.emailDefaultRecipient': 'Recipient Name',
    'hero.emailDefaultIssueDate': 'Issue Date',
    'hero.emailDefaultCategory': 'Category',
    'hero.emailDefaultDescription': 'Description',
    'hero.emailDefaultNA': 'N/A',
    
    // About Section
    'about.title': 'About',
    'about.ourMission': 'Our Mission',
    'about.keyFeatures': 'Key Features',
    'about.description1': 'Our multilingual E-Certificate Management Platform revolutionizes how organizations create, manage, and verify certificates for various programs including trainings, internships, MoUs, and industrial visits.',
    'about.description2': 'Built with modern technology stack including Next.js, Shadcn UI, Tailwind CSS, and Supabase, our platform ensures scalability, security, and seamless user experience across multiple languages.',
    'about.description3': 'We empower organizations to streamline their certificate management process, reduce administrative overhead, and provide instant verification capabilities to enhance credibility and trust.',
    'about.featuresDescription': 'Discover the powerful features that make our platform the ideal solution for modern certificate management.',
    'about.features.multiUser': 'Multi-User Management',
    'about.features.multiUserDesc': 'Support for Admin, Team, and Public access levels with role-based permissions.',
    'about.features.professional': 'Professional Certificates',
    'about.features.professionalDesc': 'Create beautiful, verifiable certificates with customizable templates and layouts.',
    'about.features.secure': 'Secure Verification',
    'about.features.secureDesc': 'Public verification system with unique URLs for each certificate.',
    'about.features.email': 'Email Integration',
    'about.features.emailDesc': 'Send certificates via email individually or in bulk with advanced filtering options.',
    
    // Footer
    'footer.quickLinks': 'Quick Links',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact Us',
    'footer.cookies': 'Cookie Policy',
    'footer.developedBy': 'Developed by',
    
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about our platform',
    'faq.q1': 'What is the E-Certificate Management Platform?',
    'faq.a1': 'Our platform is a digital solution designed to streamline certificate creation, management, and verification for organizations. It supports various certificate types including training programs, internships, MoUs, and industrial visits, with multilingual support and role-based access controls.',
    'faq.q2': 'Which languages are available?',
    'faq.a2': 'The platform currently supports English and Indonesian with seamless language switching. Additional languages may be added based on user feedback and requirements.',
    'faq.q3': 'What are the user roles and permissions?',
    'faq.a3': 'Three access levels are available: Admin (full system access), Team (create, view, and edit certificates), and Public (search and view certificates only). Each role has specific permissions tailored to different organizational needs.',
    'faq.q4': 'How do I create a certificate?',
    'faq.a4': 'The process involves three main steps: First, create a template by uploading your certificate design. Next, configure the template layout by adding and positioning text layers such as recipient name, certificate number, and dates. Finally, go to the Certificates menu to generate certificates by either selecting members from your database or importing data from an Excel file. The system will automatically populate the template with your data to create professional certificates.',
    'faq.q5': 'Can I bulk import certificates from Excel?',
    'faq.a5': 'Yes, bulk import is supported. Upload an Excel file containing member information, and the system will automatically generate multiple certificates in one operation, saving time and reducing manual data entry.',
    'faq.q6': 'How is certificate security and verification handled?',
    'faq.a6': 'Each certificate is assigned a unique verification URL that enables public authenticity checks. The platform employs industry-standard security protocols and encryption to safeguard all data and transactions.',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Platform usage and insights',
    'analytics.totalCertificates': 'Total Certificates',
    'analytics.totalTemplates': 'Total Templates',
    'analytics.totalUsers': 'Total Users',
    'analytics.recentActivity': 'Recent Activity',
    'analytics.keyStatistics': 'Key Statistics',
    'analytics.certificatesIssued': 'Certificates Issued',
    'analytics.templatesAvailable': 'Templates Available',
    'analytics.registeredMembers': 'Registered Members',
    'analytics.certificateCategories': 'Certificate Categories',
    
    // Members
    'members.title': 'Members',
    'members.subtitle': 'Manage members and their certificates',
    'members.addMember': 'Add Member',
    'members.viewCertificates': 'View Certificates',
    'members.loadCertificatesFailed': 'Failed to load certificates',
    'members.loadMembersFailed': 'Failed to load members',
    'members.loadingPage': 'Preparing members page...',
    'members.accessDenied.title': 'Access Denied',
    'members.accessDenied.message': 'You do not have permission to view this page.',
    'members.nameRequired': 'Full name is required',
    'members.updateSuccess': 'Member updated successfully',
    'members.updateFailed': 'Failed to update member',
    'members.addSuccess': 'Member added successfully',
    'members.addFailed': 'Failed to add member',
    'members.deleteNoPermission': "You don't have permission to delete members",
    'members.deleteSuccess': 'Member deleted successfully',
    'members.deleteFailed': 'Failed to delete member',
    'members.adding': 'Adding...',
    'members.saving': 'Saving...',
    'members.saveChanges': 'Save Changes',
    'members.certificateImagePreview': 'Certificate Image',
    'members.noImage': 'No image',
    'members.loading': 'Loading members...',
    'members.loadingMembers': 'Loading members...',
    'members.loadingMessage': 'Please wait while we fetch your members.',
    'members.errorLoading': 'Error loading members',
    'members.tryAgain': 'Try Again',
    'members.noMembersTitle': 'No members yet',
    'members.noMembersMessage': 'Start by adding your first member.',
    'members.certificates': 'Certificates',
    'members.noCertificatesForMember': 'No certificates for this member',
    'members.editMember': 'Edit Member',
    'members.form.fullName': 'Full Name',
    'members.form.fullNamePlaceholder': 'e.g. John Doe',
    'members.form.email': 'Email',
    'members.form.organization': 'Organization',
    'members.form.phone': 'Phone',
    'members.form.job': 'Job',
    'members.form.dob': 'Date of Birth',
    'members.form.address': 'Address',
    'members.form.city': 'City',
    'members.form.notes': 'Notes',
    'members.form.optional': 'Optional',
    'members.table.name': 'Name',
    'members.table.organization': 'Organization',
    'members.table.email': 'Email',
    'members.table.phone': 'Phone',
    'members.table.contact': 'Contact',
    'members.excel.title': 'Excel Import Format',
    'members.excel.description': 'Please prepare your Excel file with the following columns',
    'members.excel.requiredColumns': 'Required Columns:',
    'members.excel.optionalColumns': 'Columns To Fill:',
    'members.excel.exampleFormat': 'Example Format:',
    'members.excel.note': 'Note:',
    'members.excel.noteText': 'Column names are case-insensitive. You can use "Name", "name", or "NAME".',
    'members.excel.cancel': 'Cancel',
    'members.excel.chooseFile': 'Choose Excel File',
    'members.excel.importing': 'Importing...',
    'members.excel.importExcel': 'Import Excel',
    'members.excel.nameRequired': 'Full name of the member (Required)',
    'members.table.job': 'Job',
    'members.table.city': 'City',
    'members.table.actions': 'Actions',
    'members.search.noResults': 'No members found',
    'members.search.noMatch': 'No members match your search',
    'members.search.clearSearch': 'Clear search',
    'members.detail.title': 'Member Information',

    // Quick Generate Modal
    'quickGenerate.title': 'Generate Certificate',
    'quickGenerate.description': 'Generate certificates by selecting a template and data source',
    'quickGenerate.selectTemplate': 'Select Template',
    'quickGenerate.chooseTemplate': 'Choose a template...',
    'quickGenerate.loadingTemplates': 'Loading templates...',
    'quickGenerate.notConfigured': 'Not Configured',
    'quickGenerate.dataSource': 'Data Source',
    'quickGenerate.selectMember': 'Select Member',
    'quickGenerate.selectMembers': 'Select Member(s)',
    'quickGenerate.uploadExcel': 'Upload Excel',
    'quickGenerate.loadingMembers': 'Loading members...',
    'quickGenerate.noOrganization': 'No Organization',
    'quickGenerate.membersSelected': 'member(s) selected',
    'quickGenerate.dateFormat': 'Date Format',
    'quickGenerate.issueDate': 'Issue Date',
    'quickGenerate.expiredDate': 'Expired Date',
    'quickGenerate.chooseExcelFile': 'Choose Excel File',
    'quickGenerate.uploadExcelHint': 'Upload .xlsx or .xls file',
    'quickGenerate.rowsLoaded': 'rows loaded',
    'quickGenerate.willGenerate': 'This will generate',
    'quickGenerate.certificatesAtOnce': 'certificate(s) at once',
    'quickGenerate.cancel': 'Cancel',
    'quickGenerate.generating': 'Generating...',
    'quickGenerate.generate': 'Generate',
    'quickGenerate.selectTemplateError': 'Please select a template',
    'quickGenerate.selectMemberError': 'Please select at least one member',
    'quickGenerate.uploadExcelError': 'Please upload Excel file',
    'quickGenerate.generateError': 'Failed to generate certificate',
    'quickGenerate.loadedRows': 'Loaded',
    'quickGenerate.rowsFromExcel': 'rows from Excel',
    'quickGenerate.parseExcelError': 'Failed to parse Excel file',
    'quickGenerate.generatingCertificates': 'Generating certificates...',
    'quickGenerate.successSingle': 'Certificate generated successfully!',
    'quickGenerate.successMultiple': 'Successfully generated',
    'quickGenerate.certificatesGenerated': 'certificate(s)!',
    
    // Navigation
    'nav.menu': 'Menu',
    
    // Error Messages - Search
    'error.search.notFound': 'Certificate not found. Please check the certificate number or link and try again.',
    'error.search.empty': 'Please enter a certificate number or name to search',
    'error.search.failed': 'Search failed. Please try again.',
    
    // Login Modal
    'login.welcomeBack': 'Welcome Back',
    'login.signInMessage': 'Sign in to your account to continue',
    'login.emailAddress': 'Email Address',
    'login.password': 'Password',
    'login.enterEmail': 'Enter your email',
    'login.enterPassword': 'Enter your password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.orContinueWith': 'Or continue with',
    
    // Auth Callback
    'auth.callback.finishingSignIn': 'Finishing sign in…',
    'auth.callback.signingYouIn': 'Signing you in…',
    'auth.callback.finalisingSession': 'Finalising session…',
    'auth.callback.settingUpAccount': 'Setting up your account…',
    'auth.callback.almostDone': 'Almost done…',
    'auth.callback.success': 'Login successful! Redirecting…',
    'auth.callback.authFailed': 'Authentication failed. Redirecting to home…',
    'auth.callback.authFailedShort': 'Authentication failed. Redirecting…',
    'auth.callback.noSession': 'No session found. Redirecting…',
    'auth.callback.errorOccurred': 'An error occurred. Redirecting…',
    'auth.callback.takeMeHome': 'Take me home',
    
    // Error Messages - Login
    'error.login.invalidEmail': 'Please enter a valid email address.',
    'error.login.invalidPassword': 'Your password must be at least 6 characters long.',
    'error.login.invalidCredentials': 'Invalid email or password.',
    
    // Search & Filter
    'search.category': 'Category',
    'search.allCategories': 'All Categories',
    'search.dateRange': 'Date Range',
    'search.startDate': 'Start Date',
    'search.endDate': 'End Date',
    'search.clearFilters': 'Clear Filters',
    'search.noResults': 'No matching results found for',
    'search.noResultsGeneral': 'No certificates found',
    'search.filteredBy': 'Filtered by',
    'search.showingResults': 'Showing results',
    'search.searchByName': 'Search by name or number...',
    'search.inCategory': 'in category',
    'search.found': 'found',
  },
  id: {
    // Navigation
    'nav.home': 'Beranda',
    'nav.about': 'Tentang',
    'nav.templates': 'Template',
    'nav.certificates': 'Sertifikat',
    'nav.faq': 'FAQ',
    'nav.management': 'Manajemen',
    'nav.explore': 'Jelajahi',
    'nav.contact': 'Kontak',
    
    // Auth
    'auth.login': 'Masuk',
    'auth.logout': 'Keluar',
    'auth.admin': 'Admin',
    'auth.team': 'Tim',
    'auth.public': 'Publik',
    
    // Templates
    'templates.title': 'Template',
    'templates.subtitle': 'Kelola dan buat template sertifikat',
    'templates.create': 'Buat Template',
    'templates.preview': 'Pratinjau',
    'templates.search': 'Cari template...',
    'templates.allCategories': 'Semua Kategori',
    'templates.noTemplates': 'Tidak ada template ditemukan',
    'templates.createNew': 'Buat Template Baru',
    'templates.loading': 'Memuat Template',
    
    // Certificates
    'certificates.title': 'Sertifikat',
    'certificates.subtitle': 'Kelola dan lacak sertifikat',
    'certificates.create': 'Buat Sertifikat',
    'certificates.certificateId': 'Nomor Sertifikat',
    'certificates.recipient': 'Penerima',
    'certificates.issuedDate': 'Tanggal Diterbitkan',
    'certificates.expiryDate': 'Tanggal Kedaluwarsa',
    'certificates.actions': 'Aksi',
    'certificates.search': 'Cari sertifikat...',
    'certificates.noCertificates': 'Tidak ada sertifikat ditemukan',
    'certificates.category': 'Kategori',
    'certificates.description': 'Deskripsi',
    'certificates.updateSuccess': 'Sertifikat berhasil diperbarui!',
    'certificates.updateFailed': 'Gagal memperbarui sertifikat',
    'certificates.deleteNoPermission': 'Anda tidak memiliki izin untuk menghapus sertifikat',
    'certificates.deleteConfirm': 'Apakah Anda yakin ingin menghapus sertifikat untuk "{name}"?\n\nNomor Sertifikat: {number}\n\nTindakan ini tidak dapat dibatalkan.',
    'certificates.deleteSuccess': 'Sertifikat untuk "{name}" berhasil dihapus!',
    'certificates.deleteFailed': 'Gagal menghapus sertifikat. Silakan coba lagi.',
    'certificates.deleting': 'Menghapus...',
    'certificates.loading': 'Memuat sertifikat...',
    'certificates.loadingMessage': 'Mohon tunggu sementara kami mengambil sertifikat Anda.',
    'certificates.errorLoading': 'Error memuat sertifikat',
    'certificates.tryAgain': 'Coba Lagi',
    'certificates.filterByDate': 'Filter berdasarkan tanggal',
    'certificates.export': 'Ekspor',
    'certificates.exportPdf': 'Ekspor sebagai PDF',
    'certificates.downloadPng': 'Unduh PNG',
    'certificates.sendEmail': 'Kirim via Email',
    'certificates.generateLink': 'Buat Link Sertifikat',
    'certificates.showing': 'Menampilkan {start}-{end} dari {total} sertifikat',
    'certificates.filteredFrom': '(difilter dari {total})',
    'certificates.previous': 'Sebelumnya',
    'certificates.next': 'Selanjutnya',
    'certificates.page': 'Halaman {current} dari {total}',
    'certificates.noCertificatesMessage': 'Coba sesuaikan kriteria pencarian Anda atau buat sertifikat baru.',
    'certificates.updateDetails': 'Perbarui detail sertifikat.',
    'certificates.selectCategory': 'Pilih kategori',
    'certificates.preview': 'Pratinjau Sertifikat',
    'certificates.previewDescription': 'Lihat detail dan informasi sertifikat',
    'certificates.certificateTitle': 'SERTIFIKAT',
    'certificates.certifyText': 'Ini untuk menyatakan bahwa',
    'certificates.completedText': 'telah berhasil menyelesaikan',
    'certificates.certificateNo': 'Nomor Sertifikat:',
    'certificates.issueDate': 'Tanggal Terbit:',
    'certificates.fallbackPreview': 'Ini adalah pratinjau fallback. Konfigurasi template text layers untuk desain sertifikat yang sepenuhnya disesuaikan.',
    'certificates.memberInfoNotAvailable': 'Informasi anggota tidak tersedia',
    'certificates.loadMemberDetailsFailed': 'Gagal memuat detail anggota',
    'certificates.generate': 'Generate',
    'certificates.viewCertificates': 'Lihat Sertifikat',
    'certificates.saveSuccessWithScore': 'Sertifikat dan Nilai berhasil disimpan! Apakah Anda ingin melihat semua sertifikat?',
    'certificates.saveSuccess': 'Sertifikat berhasil disimpan! Apakah Anda ingin melihat semua sertifikat?',
    
    // Common
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.close': 'Tutup',
    'common.edit': 'Edit',
    'common.delete': 'Hapus',
    'common.preview': 'Pratinjau',
    'common.loading': 'Memuat...',
    'common.tryAgain': 'Coba Lagi',
    
    // Footer
    'footer.multilingual': 'Platform Multibahasa',
    'footer.phone': '+6281380935185',
    'footer.email': 'fahrirafa.rpl1@gmail.com',
    'footer.location': 'Malang',
    
    // Language
    'language.english': 'English',
    'language.indonesia': 'Indonesia',
    'language.switch': 'Ganti Bahasa',
    
    // Theme
    'theme.switch': 'Ganti Tema',
    'theme.light': 'Terang',
    'theme.dark': 'Gelap',
    
    // Hero Section
    'hero.title': 'Cari Sertifikat',
    'hero.searchButton': 'Cari',
    'hero.searching': 'Mencari...',
    'hero.certificatePreview': 'Pratinjau Sertifikat',
    'hero.close': 'Tutup',
    'hero.recipient': 'Nama',
    'hero.category': 'Kategori',
    'hero.template': 'Template',
    'hero.issued': 'Diterbitkan',
    'hero.expires': 'Kadaluarsa',
    'hero.noPreviewImage': 'Tidak ada gambar pratinjau',
    'hero.certificate': 'sertifikat',
    'hero.certificates': 'sertifikat',
    'hero.viewFullImage': 'Klik untuk melihat penuh',
    'hero.export': 'Ekspor',
    'hero.exportAsPDF': 'Ekspor sebagai PDF',
    'hero.downloadPNG': 'Unduh PNG',
    'hero.sendViaEmail': 'Kirim via Email',
    'hero.imageNotAvailable': 'Gambar sertifikat tidak tersedia untuk diekspor',
    'hero.pdfLibraryMissing': 'Library PDF tidak ditemukan. Silakan install dependensi \'jspdf\'.',
    'hero.pdfExported': 'PDF berhasil diekspor',
    'hero.pngDownloaded': 'PNG berhasil diunduh',
    'hero.noPublicLink': 'Sertifikat tidak memiliki ID link publik',
    'hero.linkCopied': 'Link sertifikat publik disalin',
    'hero.linkGenerateFailed': 'Gagal membuat link sertifikat',
    'hero.linkShareable': 'Link dapat dibagikan melalui WhatsApp, Email, atau platform lainnya',
    'hero.imageNotAvailableShort': 'Gambar sertifikat tidak tersedia',
    'hero.emailQueued': 'Email berhasil diantrekan! Pratinjau dibuka di tab baru',
    'hero.loadCategoriesFailed': 'Gagal memuat kategori',
    'hero.generateLink': 'Buat Link Sertifikat',
    'hero.certificateImage': 'Gambar Sertifikat',
    'hero.sendEmailTitle': 'Kirim Sertifikat via Email',
    'hero.sendEmailSubtitle': 'Konfigurasi detail email',
    'hero.certificatePreviewLabel': 'Pratinjau Sertifikat:',
    'hero.recipientEmail': 'Email Penerima',
    'hero.subject': 'Subjek',
    'hero.message': 'Pesan',
    'hero.emailSubjectPlaceholder': 'Subjek email',
    'hero.emailMessagePlaceholder': 'Pesan email',
    'hero.cancel': 'Batal',
    'hero.sendEmail': 'Kirim Email',
    'hero.sending': 'Mengirim...',
    'hero.emailSentSuccess': 'Email berhasil dikirim ke',
    'hero.emailValidationRequired': 'Email penerima wajib diisi',
    'hero.emailValidationInvalid': 'Silakan masukkan alamat email yang valid',
    'hero.subjectRequired': 'Subjek wajib diisi',
    'hero.messageRequired': 'Pesan wajib diisi',
    'hero.emailInvalidFields': 'Alamat email tidak valid atau ada field yang belum diisi',
    'hero.emailServiceUnavailable': 'Layanan email tidak tersedia',
    'hero.emailServerError': 'Kesalahan server. Silakan coba lagi nanti.',
    'hero.emailSendFailed': 'Gagal mengirim email. Silakan coba lagi.',
    'hero.emailPrepareFailed': 'Gagal mempersiapkan email',
    'hero.exportPdfFailed': 'Gagal mengekspor PDF',
    'hero.exportPngFailed': 'Gagal mengekspor PNG',
    'hero.fetchImageFailed': 'Gagal mengambil gambar',
    'hero.emailDefaultSubject': 'Sertifikat #{number}',
    'hero.emailDefaultSubjectNoNumber': 'Sertifikat Anda',
    'hero.emailDefaultGreeting': 'Yth.',
    'hero.emailDefaultInfo': 'Informasi Sertifikat:',
    'hero.emailDefaultCertNumber': 'Nomor Sertifikat',
    'hero.emailDefaultRecipient': 'Nama Penerima',
    'hero.emailDefaultIssueDate': 'Tanggal Terbit',
    'hero.emailDefaultCategory': 'Kategori',
    'hero.emailDefaultDescription': 'Deskripsi',
    'hero.emailDefaultNA': 'Tidak Ada',
    
    // About Section
    'about.title': 'Tentang E-Certificate',
    'about.ourMission': 'Misi Kami',
    'about.keyFeatures': 'Fitur Utama',
    'about.description1': 'Platform Manajemen E-Certificate multibahasa kami merevolusi cara organisasi membuat, mengelola, dan memverifikasi sertifikat untuk berbagai program termasuk pelatihan, magang, MoU, dan kunjungan industri.',
    'about.description2': 'Dibangun dengan teknologi modern termasuk Next.js, Shadcn UI, Tailwind CSS, dan Supabase, platform kami memastikan skalabilitas, keamanan, dan pengalaman pengguna yang mulus di berbagai bahasa.',
    'about.description3': 'Kami memberdayakan organisasi untuk menyederhanakan proses manajemen sertifikat mereka, mengurangi beban administrasi, dan menyediakan kemampuan verifikasi instan untuk meningkatkan kredibilitas dan kepercayaan.',
    'about.featuresDescription': 'Temukan fitur-fitur canggih yang menjadikan platform kami solusi ideal untuk manajemen sertifikat modern.',
    'about.features.multiUser': 'Manajemen Multi-Pengguna',
    'about.features.multiUserDesc': 'Dukungan untuk level akses Admin, Tim, dan Publik dengan izin berbasis peran.',
    'about.features.professional': 'Sertifikat Profesional',
    'about.features.professionalDesc': 'Buat sertifikat yang indah dan dapat diverifikasi dengan template dan tata letak yang dapat disesuaikan.',
    'about.features.secure': 'Verifikasi Aman',
    'about.features.secureDesc': 'Sistem verifikasi publik dengan URL unik untuk setiap sertifikat.',
    'about.features.email': 'Integrasi Email',
    'about.features.emailDesc': 'Kirim sertifikat melalui email secara individual atau massal dengan opsi filter lanjutan.',
    
    // Footer
    'footer.quickLinks': 'Tautan Cepat',
    'footer.legal': 'Legal',
    'footer.privacy': 'Kebijakan Privasi',
    'footer.terms': 'Syarat Layanan',
    'footer.contact': 'Hubungi Kami',
    'footer.cookies': 'Kebijakan Cookie',
    'footer.developedBy': 'Dikembangkan oleh',
    
    
    // FAQ
    'faq.title': 'Pertanyaan yang Sering Diajukan',
    'faq.subtitle': 'Temukan jawaban untuk pertanyaan umum tentang platform kami',
    'faq.q1': 'Apa itu Platform Manajemen E-Certificate?',
    'faq.a1': 'Platform kami adalah solusi digital untuk mempermudah pembuatan, pengelolaan, dan verifikasi sertifikat bagi organisasi. Mendukung berbagai jenis sertifikat seperti program pelatihan, magang, MoU, dan kunjungan industri, dengan dukungan multibahasa dan kontrol akses berbasis peran.',
    'faq.q2': 'Bahasa apa saja yang tersedia?',
    'faq.a2': 'Platform saat ini mendukung bahasa Inggris dan Indonesia dengan peralihan bahasa yang mulus. Bahasa tambahan dapat ditambahkan berdasarkan masukan dan kebutuhan pengguna.',
    'faq.q3': 'Apa saja peran pengguna dan izinnya?',
    'faq.a3': 'Tersedia tiga level akses: Admin (akses penuh sistem), Tim (membuat, melihat, dan mengedit sertifikat), serta Publik (hanya mencari dan melihat sertifikat). Setiap peran memiliki izin spesifik yang disesuaikan dengan kebutuhan organisasi.',
    'faq.q4': 'Bagaimana cara membuat sertifikat?',
    'faq.a4': 'Proses pembuatan sertifikat terdiri dari tiga langkah utama: Pertama, buat template dengan mengunggah desain sertifikat Anda. Selanjutnya, atur layout template dengan menambahkan dan memposisikan layer teks seperti nama penerima, nomor sertifikat, dan tanggal. Terakhir, akses menu Sertifikat untuk melakukan generate sertifikat dengan memilih data anggota member yang tersedia atau mengimpor data menggunakan file Excel. Sistem akan secara otomatis mengisi template dengan data Anda untuk menghasilkan sertifikat yang profesional.',
    'faq.q5': 'Bisakah mengimpor sertifikat secara massal dari Excel?',
    'faq.a5': 'Ya, impor massal didukung. Unggah file Excel berisi data anggota, dan sistem akan otomatis menghasilkan beberapa sertifikat sekaligus, menghemat waktu dan mengurangi entri data manual.',
    'faq.q6': 'Bagaimana keamanan dan verifikasi sertifikat?',
    'faq.a6': 'Setiap sertifikat memiliki URL verifikasi unik yang memungkinkan pemeriksaan keaslian publik. Platform menggunakan protokol keamanan dan enkripsi standar industri untuk melindungi semua data dan transaksi.',
    
    // Analytics
    'analytics.title': 'Analitik',
    'analytics.subtitle': 'Penggunaan platform dan wawasan',
    'analytics.totalCertificates': 'Total Sertifikat',
    'analytics.totalTemplates': 'Total Template',
    'analytics.totalUsers': 'Total Pengguna',
    'analytics.recentActivity': 'Aktivitas Terbaru',
    'analytics.keyStatistics': 'Statistik Utama',
    'analytics.certificatesIssued': 'Sertifikat Diterbitkan',
    'analytics.templatesAvailable': 'Template Tersedia',
    'analytics.registeredMembers': 'Anggota Terdaftar',
    'analytics.certificateCategories': 'Kategori Sertifikat',
    
    // Members
    'members.title': 'Anggota',
    'members.subtitle': 'Kelola anggota dan sertifikatnya',
    'members.addMember': 'Tambah Anggota',
    'members.viewCertificates': 'Lihat Sertifikat',
    'members.loadCertificatesFailed': 'Gagal memuat sertifikat',
    'members.loadMembersFailed': 'Gagal memuat data anggota',
    'members.loadingPage': 'Menyiapkan halaman anggota...',
    'members.accessDenied.title': 'Akses Ditolak',
    'members.accessDenied.message': 'Anda tidak memiliki izin untuk melihat halaman ini.',
    'members.nameRequired': 'Nama lengkap wajib diisi',
    'members.updateSuccess': 'Data anggota berhasil diperbarui',
    'members.updateFailed': 'Gagal memperbarui data anggota',
    'members.addSuccess': 'Anggota berhasil ditambahkan',
    'members.addFailed': 'Gagal menambahkan anggota',
    'members.deleteNoPermission': 'Anda tidak memiliki izin untuk menghapus anggota',
    'members.deleteSuccess': 'Anggota berhasil dihapus',
    'members.deleteFailed': 'Gagal menghapus anggota',
    'members.adding': 'Menambahkan...',
    'members.saving': 'Menyimpan...',
    'members.saveChanges': 'Simpan Perubahan',
    'members.certificateImagePreview': 'Gambar Sertifikat',
    'members.noImage': 'Tidak ada gambar',
    'members.loading': 'Memuat data anggota...',
    'members.loadingMembers': 'Memuat data anggota...',
    'members.loadingMessage': 'Mohon tunggu sementara kami mengambil data anggota Anda.',
    'members.errorLoading': 'Error memuat anggota',
    'members.tryAgain': 'Coba Lagi',
    'members.noMembersTitle': 'Belum ada anggota',
    'members.noMembersMessage': 'Mulai dengan menambahkan anggota pertama Anda.',
    'members.certificates': 'Sertifikat',
    'members.noCertificatesForMember': 'Tidak ada sertifikat untuk anggota ini',
    'members.editMember': 'Edit Anggota',
    'members.form.fullName': 'Nama Lengkap',
    'members.form.fullNamePlaceholder': 'contoh: Budi Santoso',
    'members.form.email': 'Email',
    'members.form.organization': 'Organisasi',
    'members.form.phone': 'Telepon',
    'members.form.job': 'Pekerjaan',
    'members.form.dob': 'Tanggal Lahir',
    'members.form.address': 'Alamat',
    'members.form.city': 'Kota',
    'members.form.notes': 'Catatan',
    'members.form.optional': 'Opsional',
    'members.table.name': 'Nama',
    'members.table.organization': 'Organisasi',
    'members.table.email': 'Email',
    'members.table.phone': 'Telepon',
    'members.table.contact': 'Kontak',
    'members.table.job': 'Pekerjaan',
    'members.table.city': 'Kota',
    'members.table.actions': 'Aksi',
    'members.excel.title': 'Format Import Excel',
    'members.excel.description': 'Silakan siapkan file Excel Anda dengan kolom-kolom berikut',
    'members.excel.requiredColumns': 'Kolom Wajib:',
    'members.excel.optionalColumns': 'Kolom Yang Diisi:',
    'members.excel.exampleFormat': 'Contoh Format:',
    'members.excel.note': 'Catatan:',
    'members.excel.noteText': 'Nama kolom tidak peka huruf besar/kecil. Anda bisa menggunakan "Name", "name", atau "NAME".',
    'members.excel.cancel': 'Batal',
    'members.excel.chooseFile': 'Pilih File Excel',
    'members.excel.importing': 'Mengimpor...',
    'members.excel.importExcel': 'Import Excel',
    'members.excel.nameRequired': 'Nama lengkap anggota (Wajib)',
    'members.search.noResults': 'Tidak ada anggota ditemukan',
    'members.search.noMatch': 'Tidak ada anggota yang cocok dengan pencarian Anda',
    'members.search.clearSearch': 'Hapus pencarian',
    'members.detail.title': 'Informasi Anggota',
    // Quick Generate Modal
    'quickGenerate.title': 'Generate Sertifikat',
    'quickGenerate.description': 'Generate sertifikat dengan memilih template dan sumber data',
    'quickGenerate.selectTemplate': 'Pilih Template',
    'quickGenerate.chooseTemplate': 'Pilih template...',
    'quickGenerate.loadingTemplates': 'Memuat template...',
    'quickGenerate.notConfigured': 'Belum Dikonfigurasi',
    'quickGenerate.dataSource': 'Sumber Data',
    'quickGenerate.selectMember': 'Pilih Anggota',
    'quickGenerate.selectMembers': 'Pilih Anggota',
    'quickGenerate.uploadExcel': 'Unggah Excel',
    'quickGenerate.loadingMembers': 'Memuat anggota...',
    'quickGenerate.noOrganization': 'Tidak Ada Organisasi',
    'quickGenerate.membersSelected': 'anggota terpilih',
    'quickGenerate.dateFormat': 'Format Tanggal',
    'quickGenerate.issueDate': 'Tanggal Terbit',
    'quickGenerate.expiredDate': 'Tanggal Kedaluwarsa',
    'quickGenerate.chooseExcelFile': 'Pilih File Excel',
    'quickGenerate.uploadExcelHint': 'Unggah file .xlsx atau .xls',
    'quickGenerate.rowsLoaded': 'baris dimuat',
    'quickGenerate.willGenerate': 'Ini akan menghasilkan',
    'quickGenerate.certificatesAtOnce': 'sertifikat sekaligus',
    'quickGenerate.cancel': 'Batal',
    'quickGenerate.generating': 'Membuat...',
    'quickGenerate.generate': 'Generate',
    'quickGenerate.selectTemplateError': 'Silakan pilih template',
    'quickGenerate.selectMemberError': 'Silakan pilih setidaknya satu anggota',
    'quickGenerate.uploadExcelError': 'Silakan unggah file Excel',
    'quickGenerate.generateError': 'Gagal membuat sertifikat',
    'quickGenerate.loadedRows': 'Dimuat',
    'quickGenerate.rowsFromExcel': 'baris dari Excel',
    'quickGenerate.parseExcelError': 'Gagal memproses file Excel',
    'quickGenerate.generatingCertificates': 'Membuat sertifikat...',
    'quickGenerate.successSingle': 'Sertifikat berhasil dibuat!',
    'quickGenerate.successMultiple': 'Berhasil membuat',
    'quickGenerate.certificatesGenerated': 'sertifikat!',
    
    // Navigation
    'nav.menu': 'Menu',
    
    // Error Messages - Search
    'error.search.notFound': 'Sertifikat tidak ditemukan. Silakan periksa nomor sertifikat atau link dan coba lagi.',
    'error.search.empty': 'Silakan masukkan nomor sertifikat atau nama untuk mencari',
    'error.search.failed': 'Pencarian gagal. Silakan coba lagi.',
    
    // Login Modal
    'login.welcomeBack': 'Selamat Datang Kembali',
    'login.signInMessage': 'Masuk ke akun Anda untuk melanjutkan',
    'login.emailAddress': 'Alamat Email',
    'login.password': 'Kata Sandi',
    'login.enterEmail': 'Masukkan email Anda',
    'login.enterPassword': 'Masukkan kata sandi Anda',
    'login.signIn': 'Masuk',
    'login.signingIn': 'Sedang masuk...',
    'login.orContinueWith': 'Atau lanjutkan dengan',
    
    // Auth Callback
    'auth.callback.finishingSignIn': 'Menyelesaikan masuk…',
    'auth.callback.signingYouIn': 'Memproses masuk Anda…',
    'auth.callback.finalisingSession': 'Menyelesaikan sesi…',
    'auth.callback.settingUpAccount': 'Menyiapkan akun Anda…',
    'auth.callback.almostDone': 'Hampir selesai…',
    'auth.callback.success': 'Login berhasil! Mengarahkan…',
    'auth.callback.authFailed': 'Autentikasi gagal. Mengarahkan ke beranda…',
    'auth.callback.authFailedShort': 'Autentikasi gagal. Mengarahkan…',
    'auth.callback.noSession': 'Sesi tidak ditemukan. Mengarahkan…',
    'auth.callback.errorOccurred': 'Terjadi kesalahan. Mengarahkan…',
    'auth.callback.takeMeHome': 'Bawa saya ke beranda',
    
    // Error Messages - Login
    'error.login.invalidEmail': 'Silakan masukkan alamat email yang valid.',
    'error.login.invalidPassword': 'Kata sandi Anda harus minimal 6 karakter.',
    'error.login.invalidCredentials': 'Email atau kata sandi salah.',
    
    // Search & Filter
    'search.category': 'Kategori',
    'search.allCategories': 'Semua Kategori',
    'search.dateRange': 'Rentang Tanggal',
    'search.startDate': 'Tanggal Mulai',
    'search.endDate': 'Tanggal Akhir',
    'search.clearFilters': 'Hapus Filter',
    'search.noResults': 'Tidak ada hasil yang cocok untuk',
    'search.noResultsGeneral': 'Tidak ada sertifikat ditemukan',
    'search.filteredBy': 'Difilter berdasarkan',
    'search.showingResults': 'Menampilkan hasil',
    'search.searchByName': 'Cari berdasarkan nama atau nomor sertifikat...',
    'search.inCategory': 'di kategori',
    'search.found': 'ditemukan',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      try {
        const saved = window.localStorage.getItem('ecert-language');
        if (saved === 'en' || saved === 'id') return saved;
      } catch {}
    }
    return 'en';
  });

  // removed unused hydrated state

  useEffect(() => {
    try {
      if (typeof window !== 'undefined') {
        window.localStorage.setItem('ecert-language', language);
      }
    } catch {}
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
