"use client";

import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
type Translations = Record<Language, Record<string, string>>;
const translations: Translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.templates': 'Templates',
    'nav.certificates': 'Certificates',
    'nav.faq': 'FAQ',
    'nav.management': 'Management',
    'nav.explore': 'Explore',
    'nav.contact': 'Contact',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Log Out',
    'auth.admin': 'Admin',
    'auth.team': 'Team',
    'auth.public': 'Public',
    
    // Templates
    'templates.title': 'Templates',
    'templates.subtitle': 'Manage and create certificate templates',
    'templates.create': 'Create Template',
    'templates.preview': 'Preview',
    'templates.search': 'Search templates...',
    'templates.allCategories': 'All Categories',
    'templates.noTemplates': 'No templates found',
    'templates.createNew': 'Create New Template',
    'templates.loading': 'Loading Templates',
    'templates.loadingMessage': 'Please wait while we fetch your templates.',
    'templates.errorLoading': 'Error loading templates',
    'templates.tryAgain': 'Try Again',
    'templates.found': 'Found {count} template{plural}',
    'templates.noTemplatesMessage': 'Create your first certificate template to get started',
    'templates.status.ready': 'Ready',
    'templates.status.draft': 'Draft',
    'templates.configure': 'Configure',
    'templates.createTitle': 'Create Template',
    'templates.createDescription': 'Define the basic details of your template.',
    'templates.editTitle': 'Edit Template',
    'templates.editDescription': 'Update template details.',
    'templates.templateName': 'Template Name',
    'templates.templateNamePlaceholder': 'Enter template name',
    'templates.category': 'Category',
    'templates.selectCategory': 'Select category',
    'templates.orientation': 'Orientation',
    'templates.landscape': 'Landscape',
    'templates.portrait': 'Portrait',
    'templates.templateMode': 'Template Mode',
    'templates.singleSide': 'Single Side',
    'templates.doubleSide': 'Double Side',
    'templates.dualTemplateInfo': 'Dual templates support both certificate and score views. You will need to upload both images.',
    'templates.templateImage': 'Template Image',
    'templates.certificateImage': 'Certificate Image (Front)',
    'templates.scoreImage': 'Score Image (Back)',
    'templates.previewImage': 'Preview Image (Thumbnail)',
    'templates.currentTemplateImage': 'Current Template Image',
    'templates.currentCertificateImage': 'Current Certificate Image (Front)',
    'templates.currentScoreImage': 'Current Score Image (Back)',
    'templates.currentPreviewImage': 'Current Preview Image (Thumbnail)',
    'templates.changeTemplateImage': 'Change Template Image',
    'templates.changeCertificateImage': 'Change Certificate Image',
    'templates.changeScoreImage': 'Change Score Image',
    'templates.changePreviewImage': 'Change Preview Image',
    'templates.noTemplateImage': 'No template image',
    'templates.noCertificateImage': 'No certificate image',
    'templates.noScoreImage': 'No score image',
    'templates.noPreviewImage': 'No preview image',
    'templates.removeNewImage': 'Remove New Image',
    'templates.removeNewCertificateImage': 'Remove New Certificate Image',
    'templates.removeNewScoreImage': 'Remove New Score Image',
    'templates.removeNewPreview': 'Remove New Preview',
    'templates.status': 'Status',
    'templates.templateNameLabel': 'Template Name:',
    'templates.categoryLabel': 'Category:',
    'templates.orientationLabel': 'Orientation:',
    'templates.statusLabel': 'Status:',
    'templates.createdLabel': 'Created:',
    'templates.typeLabel': 'Type:',
    'templates.usageLabel': 'Usage:',
    'templates.doubleSidedType': 'Double-sided (Certificate + Score)',
    'templates.usedBy': 'Used by {count} certificate(s)',
    'templates.configureLayout': 'Configure Layout',
    'templates.createSuccess': 'Template created successfully!',
    'templates.createFailed': 'Failed to create template',
    'templates.updateSuccess': 'Template updated successfully!',
    'templates.updateFailed': 'Failed to update template',
    'templates.deleteNoPermission': "You don't have permission to delete templates",
    'templates.deleteSuccess': 'Template "{name}" deleted successfully!',
    'templates.deleteFailed': 'Failed to delete template',
    'templates.deleteConfirm': 'Are you sure you want to delete "{name}"? This action cannot be undone and will also delete the associated image file.',
    'templates.cannotDeleteInUse': 'Cannot delete "{name}" because it is being used by {count} certificate(s). Please delete the certificates first.',
    'templates.cannotVerifyUsage': 'Could not verify if template is in use. Proceeding with deletion...',
    'templates.fillTemplateName': 'Please fill in Template Name',
    'templates.selectCategoryValidation': 'Please select a Category',
    'templates.uploadCertificateImage': 'Please upload Certificate Image (Front)',
    'templates.uploadScoreImage': 'Please upload Score Image (Back)',
    'templates.uploadTemplateImage': 'Please upload Template Image',
    'templates.fillRequiredFields': 'Please fill in all required fields',
    'templates.certificateImageRequired': 'Certificate image is required for dual templates',
    'templates.scoreImageRequired': 'Score image is required for dual templates',
    'templates.templateImageRequired': 'Template image is required',
    'templates.invalidFileType': 'Invalid file type. Only JPG, JPEG, and PNG are allowed.',
    'templates.fileTooLarge': 'File size too large. Maximum size is 10MB.',
    
    // Template Configure
    'configure.noTemplateId': 'No template ID provided',
    'configure.templateNotFound': 'Template not found',
    'configure.failedToLoad': 'Failed to load template',
    'configure.newLayerAdded': 'New layer added. ⚠️ Remember to click Save!',
    'configure.cannotDeleteRequired': 'Cannot delete required field',
    'configure.cannotDeleteIssueDate': 'Cannot delete required field: issue_date',
    'configure.layerDeleted': 'Text layer "{id}" deleted. ⚠️ Remember to click Save to persist!',
    'configure.missingRequiredFields': 'Missing required fields: {fields}',
    'configure.missingIssueDate': 'Missing required field: issue_date',
    'configure.saveSuccess': 'Layout saved successfully!',
    'configure.saveFailed': 'Failed to save layout',
    'configure.certificateMode': 'Certificate',
    'configure.scoreMode': 'Score',
    'configure.addTextLayer': 'Add Text Layer',
    'configure.preview': 'Preview',
    'configure.fontSize': 'Font Size',
    'configure.fontWeight': 'Font Weight',
    'configure.fontFamily': 'Font Family',
    'configure.textColor': 'Text Color',
    'configure.textAlign': 'Text Align',
    'configure.maxWidth': 'Max Width',
    'configure.lineHeight': 'Line Height',
    'configure.position': 'Position',
    'configure.x': 'X',
    'configure.y': 'Y',
    'configure.templatePreview': 'Template Preview',
    'configure.templateName': 'Template Name',
    'configure.category': 'Category',
    'configure.format': 'Format',
    'configure.previewTemplate': 'Preview Template',
    'configure.save': 'Save',
    'configure.saving': 'Saving...',
    'configure.backToTemplates': 'Back to Templates',
    'configure.textLayers': 'Text Layers',
    'configure.photoLayers': 'Photo Layers',
    'configure.addPhotoLayer': 'Add Photo Layer',
    'configure.uploadPhoto': 'Upload Photo',
    'configure.deletePhoto': 'Delete Photo',
    'configure.rememberToSave': 'Remember to click Save!',
    'configure.photoUploaded': 'Photo uploaded!',
    'configure.photoDeleted': 'Photo layer deleted.',
    'configure.fontStyle': 'Font Style',
    'configure.textDecoration': 'Text Decoration',
    'configure.bold': 'Bold',
    'configure.italic': 'Italic',
    'configure.underline': 'Underline',
    'configure.normal': 'Normal',
    'configure.left': 'Left',
    'configure.center': 'Center',
    'configure.right': 'Right',
    'configure.justify': 'Justify',
    'configure.addLayer': 'Add Layer',
    'configure.loading': 'Loading template...',
    'configure.front': 'Front',
    'configure.back': 'Back',
    'configure.required': 'Required',
    'configure.xPosition': 'X Position',
    'configure.yPosition': 'Y Position',
    'configure.frontAboveText': 'Front (above text)',
    'configure.backBehindText': 'Back (behind text)',
    'configure.defaultText': 'Default Text',
    'configure.use': 'Use',
    'configure.weight': 'Weight',
    'configure.delete': 'Delete',
    'configure.upload': 'Upload',
    'configure.uploadingPhoto': 'Uploading...',
    'configure.failedToUpload': 'Failed to upload photo',
    'configure.failedToDeletePhoto': 'Failed to delete photo from storage',
    
    // Certificates
    'certificates.title': 'Certificates',
    'certificates.subtitle': 'Manage and track certificates',
    'certificates.create': 'Create Certificate',
    'certificates.certificateId': 'Certificate Number',
    'certificates.certificateNumber': 'Certificate Number',
    'certificates.recipientName': 'Name',
    'certificates.recipient': 'Recipient',
    'certificates.issuedDate': 'Issued Date',
    'certificates.expiryDate': 'Expiry Date',
    'certificates.actions': 'Actions',
    'certificates.search': 'Search certificates...',
    'certificates.noCertificates': 'No certificates found',
    'certificates.category': 'Category',
    'certificates.description': 'Description',
    'certificates.front': 'Front',
    'certificates.back': 'Back',
    'certificates.updateSuccess': 'Certificate updated successfully!',
    'certificates.updateFailed': 'Failed to update certificate',
    'certificates.deleteNoPermission': "You don't have permission to delete certificates",
    'certificates.deleteConfirm': 'Are you sure you want to delete certificate for "{name}"?\n\nCertificate Number: {number}\n\nThis action cannot be undone.',
    'certificates.deleteSuccess': 'Certificate for "{name}" deleted successfully!',
    'certificates.deleteFailed': 'Failed to delete certificate. Please try again.',
    'certificates.deleteCertificate': 'Delete Certificate',
    'certificates.deleting': 'Deleting...',
    'certificates.loading': 'Loading certificates...',
    'certificates.loadingMessage': 'Please wait while we fetch your certificates.',
    'certificates.errorLoading': 'Error loading certificates',
    'certificates.tryAgain': 'Try Again',
    'certificates.filterByDate': 'Filter by date',
    'certificates.export': 'Export',
    'certificates.exportPdf': 'Export as PDF',
    'certificates.downloadPng': 'Download PNG',
    'certificates.sendEmail': 'Send via Email',
    'certificates.generateLink': 'Generate Certificate Link',
    'certificates.showing': 'Showing {start}-{end} of {total} certificates',
    'certificates.filteredFrom': '(filtered from {total})',
    'certificates.previous': 'Previous',
    'certificates.next': 'Next',
    'certificates.page': 'Page {current} of {total}',
    'certificates.noCertificatesMessage': 'Try adjusting your search criteria or create a new certificate.',
    'certificates.updateDetails': 'Update certificate details.',
    'certificates.selectCategory': 'Select category',
    'certificates.preview': 'Certificate',
    'certificates.previewDescription': 'View certificate details and information',
    'certificates.certificateTitle': 'CERTIFICATE',
    'certificates.certifyText': 'This is to certify that',
    'certificates.completedText': 'has successfully completed the',
    'certificates.certificateNo': 'Certificate No:',
    'certificates.issueDate': 'Issue Date:',
    'certificates.fallbackPreview': 'This is a fallback preview. Configure template text layers for a fully customized certificate design.',
    'certificates.memberInfoNotAvailable': 'Data Information not available',
    'certificates.loadMemberDetailsFailed': 'Failed to load data details',
    'certificates.generate': 'Generate',
    'certificates.viewCertificates': 'View Certificates',
    'certificates.saveSuccessWithScore': 'Certificate and Score saved successfully! Would you like to view all certificates?',
    'certificates.saveSuccess': 'Certificate saved successfully! Would you like to view all certificates?',
    'certificates.editCertificate': 'Edit Certificate',
    'certificates.saveChanges': 'Save Changes',
    'certificates.selectCategoryOption': 'Select...',
    'certificates.descriptionPlaceholder': 'Optional description...',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.preview': 'Preview',
    'common.loading': 'Loading...',
    'common.tryAgain': 'Try Again',
    'common.saving': 'Saving...',
    

    
    // Language
    'language.english': 'English',
    'language.indonesia': 'Indonesia',
    'language.switch': 'Switch Language',
    
    // Theme
    'theme.switch': 'Switch Theme',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    
    // Hero Section
    'hero.title': 'Search Certificate',
    'hero.searchButton': 'Search',
    'hero.searching': 'Searching...',
    'hero.certificatePreview': 'Certificate Preview',
    'hero.close': 'Close',
    'hero.recipient': 'Name',
    'hero.noCertificate': 'No Certificate',
    'hero.category': 'Category',
    'hero.template': 'Template',
    'hero.issued': 'Issued',
    'hero.expires': 'Expires',
    'hero.noPreviewImage': 'No preview image',
    'hero.certificate': 'certificate',
    'hero.certificates': 'certificates',
    'hero.viewFullImage': 'Click to view full image',
    'hero.viewDetails': 'View Details',
    'hero.export': 'Export',
    'hero.exportAsPDF': 'Export as PDF',
    'hero.downloadPNG': 'Download PNG',
    'hero.sendViaEmail': 'Send via Email',
    'hero.imageNotAvailable': 'Certificate image not available to export',
    'hero.pdfLibraryMissing': 'PDF library missing. Please install \'jspdf\' dependency.',
    'hero.pdfExported': 'PDF exported',
    'hero.pngDownloaded': 'PNG downloaded successfully',
    'hero.noPublicLink': 'Certificate does not have a public link ID',
    'hero.linkCopied': 'Public certificate link copied',
    'hero.linkGenerateFailed': 'Failed to generate certificate link',
    'hero.linkShareable': 'Link can be shared via WhatsApp, Email, or other platforms',
    'hero.imageNotAvailableShort': 'Certificate image not available',
    'hero.emailQueued': 'Email queued successfully! Preview opened in new tab',
    'hero.loadCategoriesFailed': 'Failed to load categories',
    'hero.generateLink': 'Generate Certificate Link',
    'hero.certificateImage': 'Certificate Image',
    'hero.sendEmailTitle': 'Send Certificate via Email',
    'hero.sendEmailSubtitle': 'Configure email details',
    'hero.certificatePreviewLabel': 'Certificate Preview:',
    'hero.recipientEmail': 'Recipient Email',
    'hero.subject': 'Subject',
    'hero.message': 'Message',
    'hero.emailSubjectPlaceholder': 'Email subject',
    'hero.emailMessagePlaceholder': 'Email message',
    'hero.cancel': 'Cancel',
    'hero.sendEmail': 'Send Email',
    'hero.sending': 'Sending...',
    'hero.emailSentSuccess': 'Email sent successfully to',
    'hero.emailValidationRequired': 'Recipient email is required',
    'hero.emailValidationInvalid': 'Please enter a valid email address',
    'hero.subjectRequired': 'Subject is required',
    'hero.messageRequired': 'Message is required',
    'hero.emailInvalidFields': 'Invalid email address or missing required fields',
    'hero.emailServiceUnavailable': 'Email service not available',
    'hero.emailServerError': 'Server error. Please try again later',
    'hero.emailSendFailed': 'Failed to send email. Please try again.',
    'hero.emailPrepareFailed': 'Failed to prepare email',
    'hero.exportPdfFailed': 'Failed to export PDF',
    'hero.exportPngFailed': 'Failed to export PNG',
    'hero.fetchImageFailed': 'Failed to fetch image',
    'hero.emailDefaultSubject': 'Certificate #{number}',
    'hero.emailDefaultSubjectNoNumber': 'Your Certificate',
    'hero.emailDefaultGreeting': 'Dear',
    'hero.emailDefaultInfo': 'Certificate Information:',
    'hero.emailDefaultCertNumber': 'Certificate Number',
    'hero.emailDefaultRecipient': 'Recipient Name',
    'hero.emailDefaultIssueDate': 'Issue Date',
    'hero.emailDefaultCategory': 'Category',
    'hero.emailDefaultDescription': 'Description',
    'hero.emailDefaultNA': 'N/A',
    'hero.attachmentPreview': 'Attachment Preview',
    
    // About Section
    'about.title': 'About',
    'about.ourMission': 'Our Mission',
    'about.keyFeatures': 'Key Features',
    'about.description1': 'Our multilingual E-Certificate Management Platform revolutionizes how organizations create, manage, and verify certificates for various programs including trainings, internships, MoUs, and industrial visits.',
    'about.description2': 'Built with modern technology stack including Next.js, Shadcn UI, Tailwind CSS, and Supabase, our platform ensures scalability, security, and seamless user experience across multiple languages.',
    'about.description3': 'We empower organizations to streamline their certificate management process, reduce administrative overhead, and provide instant verification capabilities to enhance credibility and trust.',
    'about.featuresDescription': 'Discover the powerful features that make our platform the ideal solution for modern certificate management.',
    'about.features.multiUser': 'Multi-User Management',
    'about.features.multiUserDesc': 'Support for Admin, Team, and Public access levels with role-based permissions.',
    'about.features.professional': 'Professional Certificates',
    'about.features.professionalDesc': 'Create beautiful, verifiable certificates with customizable templates and layouts.',
    'about.features.secure': 'Secure Verification',
    'about.features.secureDesc': 'Public verification system with unique URLs for each certificate.',
    'about.features.email': 'Email Integration',
    'about.features.emailDesc': 'Send certificates via email individually or in bulk with advanced filtering options.',
    

    
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about our platform',
    'faq.q1': 'What is the E-Certificate Management Platform?',
    'faq.a1': 'Our platform is a digital solution designed to streamline certificate creation, management, and verification for organizations. It supports various certificate types including training programs, internships, MoUs, and industrial visits, with multilingual support and role-based access controls.',
    'faq.q2': 'Which languages are available?',
    'faq.a2': 'The platform currently supports English and Indonesian with seamless language switching. Additional languages may be added based on user feedback and requirements.',
    'faq.q3': 'What are the user roles and permissions?',
    'faq.a3': 'Three access levels are available: Admin (full system access), Team (create, view, and edit certificates), and Public (search and view certificates only). Each role has specific permissions tailored to different organizational needs.',
    'faq.q4': 'How do I create a certificate?',
    'faq.a4': 'The process involves three main steps: First, create a template by uploading your certificate design. Next, configure the template layout by adding and positioning text layers such as recipient name, certificate number, and dates. Finally, go to the Certificates menu to generate certificates by either selecting data from your database or importing data from an Excel file. The system will automatically populate the template with your data to create professional certificates.',
    'faq.q5': 'Can I bulk import certificates from Excel?',
    'faq.a5': 'Yes, bulk import is supported. Upload an Excel file containing data information, and the system will automatically generate multiple certificates in one operation, saving time and reducing manual data entry.',
    'faq.q6': 'How is certificate security and verification handled?',
    'faq.a6': 'Each certificate is assigned a unique verification URL that enables public authenticity checks. The platform employs industry-standard security protocols and encryption to safeguard all data and transactions.',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Platform usage and insights',
    'analytics.totalCertificates': 'Total Certificates',
    'analytics.totalTemplates': 'Total Templates',
    'analytics.totalUsers': 'Total Users',
    'analytics.recentActivity': 'Recent Activity',
    'analytics.keyStatistics': 'Key Statistics',
    'analytics.certificatesIssued': 'Certificates Issued',
    'analytics.templatesAvailable': 'Templates Available',
    'analytics.registeredMembers': 'Registered data',
    'analytics.certificateCategories': 'Certificate Categories',
    
    // Members (Data)
    'members.title': 'Data',
    'members.subtitle': 'Manage data and their certificates',
    'members.addMember': 'Add Data',
    'members.viewCertificates': 'View Certificates',
    'members.loadCertificatesFailed': 'Failed to load certificates',
    'members.loadMembersFailed': 'Failed to load data',
    'members.loadingPage': 'Preparing data page...',
    'members.accessDenied.title': 'Access Denied',
    'members.accessDenied.message': 'You do not have permission to view this page.',
    'members.nameRequired': 'Full name is required',
    'members.updateSuccess': 'Data updated successfully',
    'members.updateFailed': 'Failed to update data',
    'members.addSuccess': 'Data added successfully',
    'members.addFailed': 'Failed to add data',
    'members.deleteNoPermission': "You don't have permission to delete data",
    'members.deleteSuccess': 'Data deleted successfully',
    'members.deleteFailed': 'Failed to delete data',
    'members.adding': 'Adding...',
    'members.saving': 'Saving...',
    'members.saveChanges': 'Save Changes',
    'members.loading': 'Loading data...',
    'members.loadingMembers': 'Loading data...',
    'members.loadingMessage': 'Please wait while we fetch your data.',
    'members.errorLoading': 'Error loading data',
    'members.tryAgain': 'Try Again',
    'members.noMembersTitle': 'No data yet',
    'members.noMembersMessage': 'Start by adding your first data.',
    'members.certificates': 'Certificates',
    'members.noCertificatesForMember': 'No certificates for this data',
    'members.editMember': 'Edit Data',
    'members.form.fullName': 'Full Name',
    'members.form.fullNamePlaceholder': 'e.g. John Doe',
    'members.form.email': 'Email',
    'members.form.organization': 'Organization',
    'members.form.phone': 'Phone',
    'members.form.job': 'Job',
    'members.form.dob': 'Date of Birth',
    'members.form.address': 'Address',
    'members.form.city': 'City',
    'members.form.notes': 'Notes',
    'members.form.optional': 'Optional',
    'members.table.name': 'Name',
    'members.table.organization': 'Organization',
    'members.table.email': 'Email',
    'members.table.phone': 'Phone',
    'members.table.contact': 'Contact',
    'members.excel.title': 'Excel Import Format',
    'members.excel.description': 'Please prepare your Excel file with the following columns',
    'members.excel.requiredColumns': 'Required Columns:',
    'members.excel.optionalColumns': 'Columns To Fill:',
    'members.excel.exampleFormat': 'Example Format:',
    'members.excel.note': 'Note:',
    'members.excel.noteText': 'Column names are case-insensitive. You can use "Name", "name", or "NAME".',
    'members.excel.cancel': 'Cancel',
    'members.excel.chooseFile': 'Choose Excel File',
    'members.excel.importing': 'Importing...',
    'members.excel.importExcel': 'Import Excel',
    'members.excel.nameRequired': 'Full name (Required)',
    'members.table.job': 'Job',
    'members.table.city': 'City',
    'members.table.actions': 'Actions',
    'members.search.noResults': 'No data found',
    'members.search.noMatch': 'No data match your search',
    'members.search.clearSearch': 'Clear search',
    'members.detail.title': 'Detailed Data',

    // Quick Generate Modal
    'quickGenerate.title': 'Generate Certificate',
    'quickGenerate.description': 'Generate certificates by selecting a template and data source',
    'quickGenerate.selectTemplate': 'Select Template',
    'quickGenerate.chooseTemplate': 'Choose a template...',
    'quickGenerate.loadingTemplates': 'Loading templates...',
    'quickGenerate.notConfigured': 'Not Configured',
    'quickGenerate.dataSource': 'Data Source',
    'quickGenerate.selectMember': 'Select Data',
    'quickGenerate.selectMembers': 'Select Data',
    'quickGenerate.uploadExcel': 'Upload Excel',
    'quickGenerate.loadingMembers': 'Loading data...',
    'quickGenerate.noOrganization': 'No Organization',
    'quickGenerate.membersSelected': 'data selected',
    'quickGenerate.dateFormat': 'Date Format',
    'quickGenerate.issueDate': 'Issue Date',
    'quickGenerate.expiredDate': 'Expired Date',
    'quickGenerate.chooseExcelFile': 'Choose Excel File',
    'quickGenerate.uploadExcelHint': 'Upload .xlsx or .xls file',
    'quickGenerate.requiredColumns': 'Required Excel Columns:',
    'quickGenerate.ensureColumns': 'Make sure your Excel file has the columns below',
    'quickGenerate.frontSide': 'Front Side',
    'quickGenerate.backSide': 'Back Side',
    'quickGenerate.rowsData': 'rows of data',
    'quickGenerate.excelDataLoaded': 'Excel Data Successfully Loaded',
    'quickGenerate.dataLoadedSuccess': 'rows loaded',
    'quickGenerate.backSideDataLoaded': 'rows of back side data loaded',
    'quickGenerate.rowsLoaded': 'rows loaded',
    'quickGenerate.next': 'Next',
    'quickGenerate.back': 'Back',
    'quickGenerate.inputScoreData': 'Input Score Data',
    'quickGenerate.selectExcelColumn': 'Select Excel column...',
    'quickGenerate.notMapped': '-- Not mapped --',
    'quickGenerate.previewData': 'Preview Data (Row 1):',
    'quickGenerate.failedReadExcel': 'Failed to read Excel file',
    'quickGenerate.failedReadBackSide': 'Failed to read back side Excel file',
    'quickGenerate.willGenerate': 'This will generate',
    'quickGenerate.certificatesAtOnce': 'certificate(s) at once',
    'quickGenerate.cancel': 'Cancel',
    'quickGenerate.generating': 'Generating...',
    'quickGenerate.generate': 'Generate',
    'quickGenerate.selectTemplateError': 'Please select a template',
    'quickGenerate.selectMemberError': 'Please select at least one data',
    'quickGenerate.uploadExcelError': 'Please upload Excel file',
    'quickGenerate.generateError': 'Failed to generate certificate',
    'quickGenerate.loadedRows': 'Loaded',
    'quickGenerate.rowsFromExcel': 'rows from Excel',
    'quickGenerate.parseExcelError': 'Failed to parse Excel file',
    'quickGenerate.generatingCertificates': 'Generating certificates...',
    'quickGenerate.successSingle': 'Certificate generated successfully!',
    'quickGenerate.successMultiple': 'Successfully generated',
    'quickGenerate.certificatesGenerated': 'certificate(s)!',
    'quickGenerate.selectMemberForScore': 'Select Member',
    'quickGenerate.enterScore': 'Enter {field}',
    
    // Categories
    'categories.title': 'Categories',
    'categories.subtitle': 'Manage certificate categories',
    'categories.create': 'Create Category',
    'categories.name': 'Name',
    'categories.actions': 'Actions',
    'categories.relatedTemplate': 'Related Template',
    
    // Navigation
    'nav.menu': 'Menu',
    
    // Error Messages - Search
    'error.search.notFound': 'Certificate not found. Please check the certificate number or link and try again.',
    'error.search.empty': 'Please enter a certificate number or name to search',
    'error.search.failed': 'Search failed. Please try again.',
    
    // Login Modal
    'login.welcomeBack': 'Welcome Back',
    'login.signInMessage': 'Sign in to your account to continue',
    'login.emailAddress': 'Email Address',
    'login.password': 'Password',
    'login.enterEmail': 'Enter your email',
    'login.enterPassword': 'Enter your password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.orContinueWith': 'Or continue with',
    
    // Auth Callback
    'auth.callback.finishingSignIn': 'Finishing sign in…',
    'auth.callback.signingYouIn': 'Signing you in…',
    'auth.callback.finalisingSession': 'Finalising session…',
    'auth.callback.settingUpAccount': 'Setting up your account…',
    'auth.callback.almostDone': 'Almost done…',
    'auth.callback.success': 'Login successful! Redirecting…',
    'auth.callback.authFailed': 'Authentication failed. Redirecting to home…',
    'auth.callback.authFailedShort': 'Authentication failed. Redirecting…',
    'auth.callback.noSession': 'No session found. Redirecting…',
    'auth.callback.errorOccurred': 'An error occurred. Redirecting…',
    'auth.callback.takeMeHome': 'Take me home',
    
    // Error Messages - Login
    'error.login.invalidEmail': 'Please enter a valid email address.',
    'error.login.invalidPassword': 'Your password must be at least 6 characters long.',
    'error.login.invalidCredentials': 'Invalid email or password.',
    
    // Search & Filter
    'search.category': 'Category',
    'search.allCategories': 'All Categories',
    'search.dateRange': 'Date Range',
    'search.startDate': 'Start Date',
    'search.endDate': 'End Date',
    'search.clearFilters': 'Clear Filters',
    'search.showingResults': 'Showing results',
    'search.foundFor': 'found for',
    'search.startSearching': 'Start Searching',
    'search.enterQuery': 'Enter a certificate number or name to search',
    'search.noResults': 'No matching results found for',
    'search.noResultsGeneral': 'No certificates found',
    'search.filteredBy': 'Filtered by',
    'search.searchByName': 'Search by name or number...',
    'search.inCategory': 'in category',
    'search.found': 'found',
    'error.search.noResults': 'No certificates found',
    'error.search.tryDifferent': 'Try adjusting your search terms or filters',
    'hero.backToHome': 'Back to Home',
    'hero.endDate': 'End Date',
    'hero.clearFilters': 'Clear Filters',
    'hero.applyFilters': 'Apply Filters',
  },
  id: {
    // Navigation
    'nav.home': 'Beranda',
    'nav.about': 'Tentang',
    'nav.templates': 'Template',
    'nav.certificates': 'Sertifikat',
    'nav.faq': 'FAQ',
    'nav.management': 'Manajemen',
    'nav.explore': 'Jelajahi',
    'nav.contact': 'Kontak',
    
    // Auth
    'auth.login': 'Masuk',
    'auth.logout': 'Keluar',
    'auth.admin': 'Admin',
    'auth.team': 'Tim',
    'auth.public': 'Publik',
    
    // Templates
    'templates.title': 'Template',
    'templates.subtitle': 'Kelola dan buat template sertifikat',
    'templates.create': 'Buat Template',
    'templates.preview': 'Pratinjau',
    'templates.search': 'Cari template...',
    'templates.allCategories': 'Semua Kategori',
    'templates.noTemplates': 'Tidak ada template ditemukan',
    'templates.createNew': 'Buat Template Baru',
    'templates.loading': 'Memuat Template',
    'templates.loadingMessage': 'Mohon tunggu sementara kami mengambil template Anda.',
    'templates.errorLoading': 'Error memuat template',
    'templates.tryAgain': 'Coba Lagi',
    'templates.found': 'Ditemukan {count} template',
    'templates.noTemplatesMessage': 'Buat template sertifikat pertama Anda untuk memulai',
    'templates.status.ready': 'Siap',
    'templates.status.draft': 'Draft',
    'templates.configure': 'Konfigurasi',
    'templates.createTitle': 'Buat Template',
    'templates.createDescription': 'Tentukan detail dasar template Anda.',
    'templates.editTitle': 'Edit Template',
    'templates.editDescription': 'Perbarui detail template.',
    'templates.templateName': 'Nama Template',
    'templates.templateNamePlaceholder': 'Masukkan nama template',
    'templates.category': 'Kategori',
    'templates.selectCategory': 'Pilih kategori',
    'templates.orientation': 'Orientasi',
    'templates.landscape': 'Landscape',
    'templates.portrait': 'Portrait',
    'templates.templateMode': 'Mode Template',
    'templates.singleSide': 'Satu Sisi',
    'templates.doubleSide': 'Dua Sisi',
    'templates.dualTemplateInfo': 'Template dual mendukung tampilan sertifikat dan nilai. Anda perlu mengunggah kedua gambar.',
    'templates.templateImage': 'Gambar Template',
    'templates.certificateImage': 'Gambar Sertifikat (Depan)',
    'templates.scoreImage': 'Gambar Nilai (Belakang)',
    'templates.previewImage': 'Gambar Pratinjau (Thumbnail)',
    'templates.currentTemplateImage': 'Gambar Template Saat Ini',
    'templates.currentCertificateImage': 'Gambar Sertifikat Saat Ini (Depan)',
    'templates.currentScoreImage': 'Gambar Nilai Saat Ini (Belakang)',
    'templates.currentPreviewImage': 'Gambar Pratinjau Saat Ini (Thumbnail)',
    'templates.changeTemplateImage': 'Ubah Gambar Template',
    'templates.changeCertificateImage': 'Ubah Gambar Sertifikat',
    'templates.changeScoreImage': 'Ubah Gambar Nilai',
    'templates.changePreviewImage': 'Ubah Gambar Pratinjau',
    'templates.noTemplateImage': 'Tidak ada gambar template',
    'templates.noCertificateImage': 'Tidak ada gambar sertifikat',
    'templates.noScoreImage': 'Tidak ada gambar nilai',
    'templates.noPreviewImage': 'Tidak ada gambar pratinjau',
    'templates.removeNewImage': 'Hapus Gambar Baru',
    'templates.removeNewCertificateImage': 'Hapus Gambar Sertifikat Baru',
    'templates.removeNewScoreImage': 'Hapus Gambar Nilai Baru',
    'templates.removeNewPreview': 'Hapus Pratinjau Baru',
    'templates.status': 'Status',
    'templates.templateNameLabel': 'Nama Template:',
    'templates.categoryLabel': 'Kategori:',
    'templates.orientationLabel': 'Orientasi:',
    'templates.statusLabel': 'Status:',
    'templates.createdLabel': 'Dibuat:',
    'templates.typeLabel': 'Tipe:',
    'templates.usageLabel': 'Penggunaan:',
    'templates.doubleSidedType': 'Dua sisi (Sertifikat + Nilai)',
    'templates.usedBy': 'Digunakan oleh {count} sertifikat',
    'templates.configureLayout': 'Konfigurasi Layout',
    'templates.createSuccess': 'Template berhasil dibuat!',
    'templates.createFailed': 'Gagal membuat template',
    'templates.updateSuccess': 'Template berhasil diperbarui!',
    'templates.updateFailed': 'Gagal memperbarui template',
    'templates.deleteNoPermission': 'Anda tidak memiliki izin untuk menghapus template',
    'templates.deleteSuccess': 'Template "{name}" berhasil dihapus!',
    'templates.deleteFailed': 'Gagal menghapus template',
    'templates.deleteConfirm': 'Apakah Anda yakin ingin menghapus "{name}"? Tindakan ini tidak dapat dibatalkan dan juga akan menghapus file gambar yang terkait.',
    'templates.cannotDeleteInUse': 'Tidak dapat menghapus "{name}" karena sedang digunakan oleh {count} sertifikat. Silakan hapus sertifikat terlebih dahulu.',
    'templates.cannotVerifyUsage': 'Tidak dapat memverifikasi apakah template sedang digunakan. Melanjutkan penghapusan...',
    'templates.fillTemplateName': 'Silakan isi Nama Template',
    'templates.selectCategoryValidation': 'Silakan pilih Kategori',
    'templates.uploadCertificateImage': 'Silakan unggah Gambar Sertifikat (Depan)',
    'templates.uploadScoreImage': 'Silakan unggah Gambar Nilai (Belakang)',
    'templates.uploadTemplateImage': 'Silakan unggah Gambar Template',
    'templates.fillRequiredFields': 'Silakan isi semua field yang wajib diisi',
    'templates.certificateImageRequired': 'Gambar sertifikat wajib untuk template dual',
    'templates.scoreImageRequired': 'Gambar nilai wajib untuk template dual',
    'templates.templateImageRequired': 'Gambar template wajib diisi',
    'templates.invalidFileType': 'Tipe file tidak valid. Hanya JPG, JPEG, dan PNG yang diizinkan.',
    'templates.fileTooLarge': 'Ukuran file terlalu besar. Ukuran maksimal adalah 10MB.',
    
    // Template Configure
    'configure.noTemplateId': 'ID template tidak diberikan',
    'configure.templateNotFound': 'Template tidak ditemukan',
    'configure.failedToLoad': 'Gagal memuat template',
    'configure.newLayerAdded': 'Layer baru ditambahkan. ⚠️ Ingat untuk klik Simpan!',
    'configure.cannotDeleteRequired': 'Tidak dapat menghapus field wajib',
    'configure.cannotDeleteIssueDate': 'Tidak dapat menghapus field wajib: issue_date',
    'configure.layerDeleted': 'Text layer "{id}" dihapus. ⚠️ Ingat untuk klik Simpan untuk menyimpan!',
    'configure.missingRequiredFields': 'Field wajib tidak ada: {fields}',
    'configure.missingIssueDate': 'Field wajib tidak ada: issue_date',
    'configure.saveSuccess': 'Layout berhasil disimpan!',
    'configure.saveFailed': 'Gagal menyimpan layout',
    'configure.certificateMode': 'Sertifikat',
    'configure.scoreMode': 'Nilai',
    'configure.addTextLayer': 'Tambah Text Layer',
    'configure.preview': 'Pratinjau',
    'configure.fontSize': 'Ukuran Font',
    'configure.fontWeight': 'Ketebalan Font',
    'configure.fontFamily': 'Jenis Font',
    'configure.textColor': 'Warna Teks',
    'configure.textAlign': 'Perataan Teks',
    'configure.maxWidth': 'Lebar Maksimal',
    'configure.lineHeight': 'Tinggi Baris',
    'configure.position': 'Posisi',
    'configure.x': 'X',
    'configure.y': 'Y',
    'configure.templatePreview': 'Pratinjau Template',
    'configure.templateName': 'Nama Template',
    'configure.category': 'Kategori',
    'configure.format': 'Format',
    'configure.previewTemplate': 'Pratinjau Template',
    'configure.save': 'Simpan',
    'configure.saving': 'Menyimpan...',
    'configure.backToTemplates': 'Kembali ke Templates',
    'configure.textLayers': 'Layer Teks',
    'configure.photoLayers': 'Layer Foto',
    'configure.addPhotoLayer': 'Tambah Layer Foto',
    'configure.uploadPhoto': 'Unggah Foto',
    'configure.deletePhoto': 'Hapus Foto',
    'configure.rememberToSave': 'Ingat untuk klik Simpan!',
    'configure.photoUploaded': 'Foto berhasil diunggah!',
    'configure.photoDeleted': 'Layer foto dihapus.',
    'configure.fontStyle': 'Gaya Font',
    'configure.textDecoration': 'Dekorasi Teks',
    'configure.bold': 'Tebal',
    'configure.italic': 'Miring',
    'configure.underline': 'Garis Bawah',
    'configure.normal': 'Normal',
    'configure.left': 'Kiri',
    'configure.center': 'Tengah',
    'configure.right': 'Kanan',
    'configure.justify': 'Rata Kanan Kiri',
    'configure.addLayer': 'Tambah Layer',
    'configure.loading': 'Memuat template...',
    'configure.front': 'Depan',
    'configure.back': 'Belakang',
    'configure.required': 'Wajib',
    'configure.xPosition': 'Posisi X',
    'configure.yPosition': 'Posisi Y',
    'configure.frontAboveText': 'Depan (di atas teks)',
    'configure.backBehindText': 'Belakang (di belakang teks)',
    'configure.defaultText': 'Teks Default',
    'configure.use': 'Gunakan',
    'configure.weight': 'Ketebalan',
    'configure.delete': 'Hapus',
    'configure.upload': 'Unggah',
    'configure.uploadingPhoto': 'Mengunggah...',
    'configure.failedToUpload': 'Gagal mengunggah foto',
    'configure.failedToDeletePhoto': 'Gagal menghapus foto dari storage',
    
    // Certificates
    'certificates.title': 'Sertifikat',
    'certificates.subtitle': 'Kelola dan lacak sertifikat',
    'certificates.create': 'Buat Sertifikat',
    'certificates.certificateId': 'Nomor Sertifikat',
    'certificates.certificateNumber': 'Nomor Sertifikat',
    'certificates.recipientName': 'Nama',
    'certificates.recipient': 'Penerima',
    'certificates.issuedDate': 'Diterbitkan',
    'certificates.expiryDate': 'Kadaluarsa',
    'certificates.actions': 'Aksi',
    'certificates.search': 'Cari sertifikat...',
    'certificates.noCertificates': 'Tidak ada sertifikat ditemukan',
    'certificates.category': 'Kategori',
    'certificates.description': 'Deskripsi',
    'certificates.front': 'Depan',
    'certificates.back': 'Belakang',
    'certificates.updateSuccess': 'Sertifikat berhasil diperbarui!',
    'certificates.updateFailed': 'Gagal memperbarui sertifikat',
    'certificates.deleteNoPermission': 'Anda tidak memiliki izin untuk menghapus sertifikat',
    'certificates.deleteConfirm': 'Apakah Anda yakin ingin menghapus sertifikat untuk "{name}"?\n\nNomor Sertifikat: {number}\n\nTindakan ini tidak dapat dibatalkan.',
    'certificates.deleteSuccess': 'Sertifikat untuk "{name}" berhasil dihapus!',
    'certificates.deleteFailed': 'Gagal menghapus sertifikat. Silakan coba lagi.',
    'certificates.deleteCertificate': 'Hapus Sertifikat',
    'certificates.deleting': 'Menghapus...',
    'certificates.loading': 'Memuat sertifikat...',
    'certificates.loadingMessage': 'Mohon tunggu sementara kami mengambil sertifikat Anda.',
    'certificates.errorLoading': 'Error memuat sertifikat',
    'certificates.tryAgain': 'Coba Lagi',
    'certificates.filterByDate': 'Filter berdasarkan tanggal',
    'certificates.export': 'Ekspor',
    'certificates.exportPdf': 'Ekspor sebagai PDF',
    'certificates.downloadPng': 'Unduh PNG',
    'certificates.sendEmail': 'Kirim via Email',
    'certificates.generateLink': 'Buat Link Sertifikat',
    'certificates.showing': 'Menampilkan {start}-{end} dari {total} sertifikat',
    'certificates.filteredFrom': '(difilter dari {total})',
    'certificates.previous': 'Sebelumnya',
    'certificates.next': 'Selanjutnya',
    'certificates.page': 'Halaman {current} dari {total}',
    'certificates.noCertificatesMessage': 'Coba sesuaikan kriteria pencarian Anda atau buat sertifikat baru.',
    'certificates.updateDetails': 'Perbarui detail sertifikat.',
    'certificates.selectCategory': 'Pilih kategori',
    'certificates.preview': 'Sertifikat',
    'certificates.previewDescription': 'Lihat detail dan informasi sertifikat',
    'certificates.certificateTitle': 'SERTIFIKAT',
    'certificates.certifyText': 'Ini untuk menyatakan bahwa',
    'certificates.completedText': 'telah berhasil menyelesaikan',
    'certificates.certificateNo': 'Nomor Sertifikat:',
    'certificates.issueDate': 'Tanggal Terbit:',
    'certificates.fallbackPreview': 'Ini adalah pratinjau fallback. Konfigurasi template text layers untuk desain sertifikat yang sepenuhnya disesuaikan.',
    'certificates.memberInfoNotAvailable': 'Informasi data tidak tersedia',
    'certificates.loadMemberDetailsFailed': 'Gagal memuat detail data',
    'certificates.generate': 'Generate',
    'certificates.viewCertificates': 'Lihat Sertifikat',
    'certificates.saveSuccessWithScore': 'Sertifikat dan Nilai berhasil disimpan! Apakah Anda ingin melihat semua sertifikat?',
    'certificates.saveSuccess': 'Sertifikat berhasil disimpan! Apakah Anda ingin melihat semua sertifikat?',
    'certificates.editCertificate': 'Edit Sertifikat',
    'certificates.saveChanges': 'Simpan Perubahan',
    'certificates.selectCategoryOption': 'Pilih...',
    'certificates.descriptionPlaceholder': 'Deskripsi opsional...',
    
    // Common
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.close': 'Tutup',
    'common.edit': 'Edit',
    'common.delete': 'Hapus',
    'common.preview': 'Pratinjau',
    'common.loading': 'Memuat...',
    'common.tryAgain': 'Coba Lagi',
    'common.saving': 'Menyimpan...',
    
  
    
    // Language
    'language.english': 'English',
    'language.indonesia': 'Indonesia',
    'language.switch': 'Ganti Bahasa',
    
    // Theme
    'theme.switch': 'Ganti Tema',
    'theme.light': 'Terang',
    'theme.dark': 'Gelap',
    
    // Hero Section
    'hero.title': 'Cari Sertifikat',
    'hero.searchButton': 'Cari',
    'hero.searching': 'Mencari...',
    'hero.certificatePreview': 'Pratinjau Sertifikat',
    'hero.close': 'Tutup',
    'hero.recipient': 'Nama',
    'hero.noCertificate': 'No Sertifikat',
    'hero.category': 'Kategori',
    'hero.template': 'Template',
    'hero.issued': 'Diterbitkan',
    'hero.expires': 'Kadaluarsa',
    'hero.noPreviewImage': 'Tidak ada gambar pratinjau',
    'hero.certificate': 'sertifikat',
    'hero.certificates': 'sertifikat',
    'hero.viewFullImage': 'Klik untuk melihat penuh',
    'hero.viewDetails': 'Lihat Detail',
    'hero.export': 'Ekspor',
    'hero.exportAsPDF': 'Ekspor sebagai PDF',
    'hero.downloadPNG': 'Unduh PNG',
    'hero.sendViaEmail': 'Kirim via Email',
    'hero.imageNotAvailable': 'Gambar sertifikat tidak tersedia untuk diekspor',
    'hero.pdfLibraryMissing': 'Library PDF tidak ditemukan. Silakan install dependensi \'jspdf\'.',
    'hero.pdfExported': 'PDF berhasil diekspor',
    'hero.pngDownloaded': 'PNG berhasil diunduh',
    'hero.noPublicLink': 'Sertifikat tidak memiliki ID link publik',
    'hero.linkCopied': 'Link sertifikat publik disalin',
    'hero.linkGenerateFailed': 'Gagal membuat link sertifikat',
    'hero.linkShareable': 'Link dapat dibagikan melalui WhatsApp, Email, atau platform lainnya',
    'hero.imageNotAvailableShort': 'Gambar sertifikat tidak tersedia',
    'hero.emailQueued': 'Email berhasil diantrekan! Pratinjau dibuka di tab baru',
    'hero.loadCategoriesFailed': 'Gagal memuat kategori',
    'hero.generateLink': 'Buat Link Sertifikat',
    'hero.certificateImage': 'Gambar Sertifikat',
    'hero.sendEmailTitle': 'Kirim Sertifikat via Email',
    'hero.sendEmailSubtitle': 'Konfigurasi detail email',
    'hero.certificatePreviewLabel': 'Pratinjau Sertifikat:',
    'hero.recipientEmail': 'Email Penerima',
    'hero.subject': 'Subjek',
    'hero.message': 'Pesan',
    'hero.emailSubjectPlaceholder': 'Subjek email',
    'hero.emailMessagePlaceholder': 'Pesan email',
    'hero.cancel': 'Batal',
    'hero.sendEmail': 'Kirim Email',
    'hero.sending': 'Mengirim...',
    'hero.emailSentSuccess': 'Email berhasil dikirim ke',
    'hero.emailValidationRequired': 'Email penerima wajib diisi',
    'hero.emailValidationInvalid': 'Silakan masukkan alamat email yang valid',
    'hero.subjectRequired': 'Subjek wajib diisi',
    'hero.messageRequired': 'Pesan wajib diisi',
    'hero.emailInvalidFields': 'Alamat email tidak valid atau ada field yang belum diisi',
    'hero.emailServiceUnavailable': 'Layanan email tidak tersedia',
    'hero.emailServerError': 'Kesalahan server. Silakan coba lagi nanti.',
    'hero.emailSendFailed': 'Gagal mengirim email. Silakan coba lagi.',
    'hero.emailPrepareFailed': 'Gagal mempersiapkan email',
    'hero.exportPdfFailed': 'Gagal mengekspor PDF',
    'hero.exportPngFailed': 'Gagal mengekspor PNG',
    'hero.fetchImageFailed': 'Gagal mengambil gambar',
    'hero.emailDefaultSubject': 'Sertifikat #{number}',
    'hero.emailDefaultSubjectNoNumber': 'Sertifikat Anda',
    'hero.emailDefaultGreeting': 'Yth.',
    'hero.emailDefaultInfo': 'Informasi Sertifikat:',
    'hero.emailDefaultCertNumber': 'Nomor Sertifikat',
    'hero.emailDefaultRecipient': 'Nama Penerima',
    'hero.emailDefaultIssueDate': 'Tanggal Terbit',
    'hero.emailDefaultCategory': 'Kategori',
    'hero.emailDefaultDescription': 'Deskripsi',
    'hero.emailDefaultNA': 'Tidak Ada',
    'hero.attachmentPreview': 'Pratinjau Lampiran',
    
    // About Section
    'about.title': 'Tentang E-Certificate',
    'about.ourMission': 'Misi Kami',
    'about.keyFeatures': 'Fitur Utama',
    'about.description1': 'Platform Manajemen E-Certificate multibahasa kami merevolusi cara organisasi membuat, mengelola, dan memverifikasi sertifikat untuk berbagai program termasuk pelatihan, magang, MoU, dan kunjungan industri.',
    'about.description2': 'Dibangun dengan teknologi modern termasuk Next.js, Shadcn UI, Tailwind CSS, dan Supabase, platform kami memastikan skalabilitas, keamanan, dan pengalaman pengguna yang mulus di berbagai bahasa.',
    'about.description3': 'Kami memberdayakan organisasi untuk menyederhanakan proses manajemen sertifikat mereka, mengurangi beban administrasi, dan menyediakan kemampuan verifikasi instan untuk meningkatkan kredibilitas dan kepercayaan.',
    'about.featuresDescription': 'Temukan fitur-fitur canggih yang menjadikan platform kami solusi ideal untuk manajemen sertifikat modern.',
    'about.features.multiUser': 'Manajemen Multi-Pengguna',
    'about.features.multiUserDesc': 'Dukungan untuk level akses Admin, Tim, dan Publik dengan izin berbasis peran.',
    'about.features.professional': 'Sertifikat Profesional',
    'about.features.professionalDesc': 'Buat sertifikat yang indah dan dapat diverifikasi dengan template dan tata letak yang dapat disesuaikan.',
    'about.features.secure': 'Verifikasi Aman',
    'about.features.secureDesc': 'Sistem verifikasi publik dengan URL unik untuk setiap sertifikat.',
    'about.features.email': 'Integrasi Email',
    'about.features.emailDesc': 'Kirim sertifikat melalui email secara individual atau massal dengan opsi filter lanjutan.',
    

    
    
    // FAQ
    'faq.title': 'Pertanyaan yang Sering Diajukan',
    'faq.subtitle': 'Temukan jawaban untuk pertanyaan umum tentang platform kami',
    'faq.q1': 'Apa itu Platform Manajemen E-Certificate?',
    'faq.a1': 'Platform kami adalah solusi digital untuk mempermudah pembuatan, pengelolaan, dan verifikasi sertifikat bagi organisasi. Mendukung berbagai jenis sertifikat seperti program pelatihan, magang, MoU, dan kunjungan industri, dengan dukungan multibahasa dan kontrol akses berbasis peran.',
    'faq.q2': 'Bahasa apa saja yang tersedia?',
    'faq.a2': 'Platform saat ini mendukung bahasa Inggris dan Indonesia dengan peralihan bahasa yang mulus. Bahasa tambahan dapat ditambahkan berdasarkan masukan dan kebutuhan pengguna.',
    'faq.q3': 'Apa saja peran pengguna dan izinnya?',
    'faq.a3': 'Tersedia tiga level akses: Admin (akses penuh sistem), Tim (membuat, melihat, dan mengedit sertifikat), serta Publik (hanya mencari dan melihat sertifikat). Setiap peran memiliki izin spesifik yang disesuaikan dengan kebutuhan organisasi.',
    'faq.q4': 'Bagaimana cara membuat sertifikat?',
    'faq.a4': 'Proses pembuatan sertifikat terdiri dari tiga langkah utama: Pertama, buat template dengan mengunggah desain sertifikat Anda. Selanjutnya, atur layout template dengan menambahkan dan memposisikan layer teks seperti nama penerima, nomor sertifikat, dan tanggal. Terakhir, akses menu Sertifikat untuk melakukan generate sertifikat dengan memilih data yang tersedia atau mengimpor data menggunakan file Excel. Sistem akan secara otomatis mengisi template dengan data Anda untuk menghasilkan sertifikat yang profesional.',
    'faq.q5': 'Bisakah mengimpor sertifikat secara massal dari Excel?',
    'faq.a5': 'Ya, impor massal didukung. Unggah file Excel berisi data, dan sistem akan otomatis menghasilkan beberapa sertifikat sekaligus, menghemat waktu dan mengurangi entri data manual.',
    'faq.q6': 'Bagaimana keamanan dan verifikasi sertifikat?',
    'faq.a6': 'Setiap sertifikat memiliki URL verifikasi unik yang memungkinkan pemeriksaan keaslian publik. Platform menggunakan protokol keamanan dan enkripsi standar industri untuk melindungi semua data dan transaksi.',
    
    // Analytics
    'analytics.title': 'Analitik',
    'analytics.subtitle': 'Penggunaan platform dan wawasan',
    'analytics.totalCertificates': 'Total Sertifikat',
    'analytics.totalTemplates': 'Total Template',
    'analytics.totalUsers': 'Total Pengguna',
    'analytics.recentActivity': 'Aktivitas Terbaru',
    'analytics.keyStatistics': 'Statistik Utama',
    'analytics.certificatesIssued': 'Sertifikat Diterbitkan',
    'analytics.templatesAvailable': 'Template Tersedia',
    'analytics.registeredMembers': 'Data Terdaftar',
    'analytics.certificateCategories': 'Kategori Sertifikat',
    
    // Members
    'members.title': 'Data',
    'members.subtitle': 'Kelola data dan sertifikatnya',
    'members.addMember': 'Tambah Data',
    'members.viewCertificates': 'Lihat Sertifikat',
    'members.loadCertificatesFailed': 'Gagal memuat sertifikat',
    'members.loadMembersFailed': 'Gagal memuat data',
    'members.loadingPage': 'Menyiapkan halaman data...',
    'members.accessDenied.title': 'Akses Ditolak',
    'members.accessDenied.message': 'Anda tidak memiliki izin untuk melihat halaman ini.',
    'members.nameRequired': 'Nama lengkap wajib diisi',
    'members.updateSuccess': 'Data berhasil diperbarui',
    'members.updateFailed': 'Gagal memperbarui data',
    'members.addSuccess': 'Data berhasil ditambahkan',
    'members.addFailed': 'Gagal menambahkan data',
    'members.deleteNoPermission': 'Anda tidak memiliki izin untuk menghapus data',
    'members.deleteSuccess': 'Data berhasil dihapus',
    'members.deleteFailed': 'Gagal menghapus data',
    'members.adding': 'Menambahkan...',
    'members.saving': 'Menyimpan...',
    'members.saveChanges': 'Simpan Perubahan',
    'members.certificateImagePreview': 'Gambar Sertifikat',
    'members.noImage': 'Tidak ada gambar',
    'members.loading': 'Memuat data...',
    'members.loadingMembers': 'Memuat data...',
    'members.loadingMessage': 'Mohon tunggu sementara kami mengambil data Anda.',
    'members.errorLoading': 'Error memuat data',
    'members.tryAgain': 'Coba Lagi',
    'members.noMembersTitle': 'Belum ada data',
    'members.noMembersMessage': 'Mulai dengan menambahkan data pertama Anda.',
    'members.certificates': 'Sertifikat',
    'members.noCertificatesForMember': 'Tidak ada sertifikat untuk data ini',
    'members.editMember': 'Edit Data',
    'members.form.fullName': 'Nama Lengkap',
    'members.form.fullNamePlaceholder': 'contoh: Budi Santoso',
    'members.form.email': 'Email',
    'members.form.organization': 'Organisasi',
    'members.form.phone': 'Telepon',
    'members.form.job': 'Pekerjaan',
    'members.form.dob': 'Tanggal Lahir',
    'members.form.address': 'Alamat',
    'members.form.city': 'Kota',
    'members.form.notes': 'Catatan',
    'members.form.optional': 'Opsional',
    'members.table.name': 'Nama',
    'members.table.organization': 'Organisasi',
    'members.table.email': 'Email',
    'members.table.phone': 'Telepon',
    'members.table.contact': 'Kontak',
    'members.table.job': 'Pekerjaan',
    'members.table.city': 'Kota',
    'members.table.actions': 'Aksi',
    'members.excel.title': 'Format Import Excel',
    'members.excel.description': 'Silakan siapkan file Excel Anda dengan kolom-kolom berikut',
    'members.excel.requiredColumns': 'Kolom Wajib:',
    'members.excel.optionalColumns': 'Kolom Yang Diisi:',
    'members.excel.exampleFormat': 'Contoh Format:',
    'members.excel.note': 'Catatan:',
    'members.excel.noteText': 'Nama kolom tidak peka huruf besar/kecil. Anda bisa menggunakan "Name", "name", atau "NAME".',
    'members.excel.cancel': 'Batal',
    'members.excel.chooseFile': 'Pilih File Excel',
    'members.excel.importing': 'Mengimpor...',
    'members.excel.importExcel': 'Import Excel',
    'members.excel.nameRequired': 'Nama lengkap (Wajib)',
    'members.search.noResults': 'Tidak ada data ditemukan',
    'members.search.noMatch': 'Tidak ada data yang cocok dengan pencarian Anda',
    'members.search.clearSearch': 'Hapus pencarian',
    'members.detail.title': 'Detail Data',
    // Quick Generate Modal
    'quickGenerate.title': 'Generate Sertifikat',
    'quickGenerate.description': 'Generate sertifikat dengan memilih template dan sumber data',
    'quickGenerate.selectTemplate': 'Pilih Template',
    'quickGenerate.chooseTemplate': 'Pilih template...',
    'quickGenerate.loadingTemplates': 'Memuat template...',
    'quickGenerate.notConfigured': 'Belum Dikonfigurasi',
    'quickGenerate.dataSource': 'Sumber Data',
    'quickGenerate.selectMember': 'Pilih Data',
    'quickGenerate.selectMembers': 'Pilih Data',
    'quickGenerate.uploadExcel': 'Unggah Excel',
    'quickGenerate.loadingMembers': 'Memuat data...',
    'quickGenerate.noOrganization': 'Tidak Ada Organisasi',
    'quickGenerate.membersSelected': 'data terpilih',
    'quickGenerate.dateFormat': 'Format Tanggal',
    'quickGenerate.issueDate': 'Tanggal Terbit',
    'quickGenerate.expiredDate': 'Tanggal Kedaluwarsa',
    'quickGenerate.chooseExcelFile': 'Pilih File Excel',
    'quickGenerate.uploadExcelHint': 'Unggah file .xlsx atau .xls',
    'quickGenerate.requiredColumns': 'Kolom Excel yang Dibutuhkan:',
    'quickGenerate.ensureColumns': 'Pastikan file Excel Anda memiliki kolom dibawah ini',
    'quickGenerate.frontSide': 'Sisi Depan',
    'quickGenerate.backSide': 'Sisi Belakang',
    'quickGenerate.rowsData': 'baris data',
    'quickGenerate.excelDataLoaded': 'Data Excel Berhasil Dimuat',
    'quickGenerate.dataLoadedSuccess': 'baris data dimuat',
    'quickGenerate.backSideDataLoaded': 'baris data back side dimuat',
    'quickGenerate.rowsLoaded': 'baris dimuat',
    'quickGenerate.next': 'Selanjutnya',
    'quickGenerate.back': 'Kembali',
    'quickGenerate.inputScoreData': 'Input Data Nilai',
    'quickGenerate.selectExcelColumn': 'Pilih kolom Excel...',
    'quickGenerate.notMapped': '-- Tidak dipetakan --',
    'quickGenerate.previewData': 'Preview Data (Baris 1):',
    'quickGenerate.failedReadExcel': 'Gagal membaca file Excel',
    'quickGenerate.failedReadBackSide': 'Gagal membaca file Excel back side',
    'quickGenerate.willGenerate': 'Ini akan menghasilkan',
    'quickGenerate.certificatesAtOnce': 'sertifikat sekaligus',
    'quickGenerate.cancel': 'Batal',
    'quickGenerate.generating': 'Membuat...',
    'quickGenerate.generate': 'Generate',
    'quickGenerate.selectTemplateError': 'Silakan pilih template',
    'quickGenerate.selectMemberError': 'Silakan pilih setidaknya satu data',
    'quickGenerate.uploadExcelError': 'Silakan unggah file Excel',
    'quickGenerate.generateError': 'Gagal membuat sertifikat',
    'quickGenerate.loadedRows': 'Dimuat',
    'quickGenerate.rowsFromExcel': 'baris dari Excel',
    'quickGenerate.parseExcelError': 'Gagal memproses file Excel',
    'quickGenerate.generatingCertificates': 'Membuat sertifikat...',
    'quickGenerate.successSingle': 'Sertifikat berhasil dibuat!',
    'quickGenerate.successMultiple': 'Berhasil membuat',
    'quickGenerate.certificatesGenerated': 'sertifikat!',
    'quickGenerate.selectMemberForScore': 'Pilih Member',
    'quickGenerate.enterScore': 'Masukkan {field}',
    
    // Categories
    'categories.title': 'Kategori',
    'categories.subtitle': 'Kelola kategori sertifikat',
    'categories.create': 'Buat Kategori',
    'categories.name': 'Nama',
    'categories.actions': 'Aksi',
    'categories.relatedTemplate': 'Template Terkait',
    
    // Navigation
    'nav.menu': 'Menu',
    
    // Error Messages - Search
    'error.search.notFound': 'Sertifikat tidak ditemukan. Silakan periksa nomor sertifikat atau link dan coba lagi.',
    'error.search.empty': 'Silakan masukkan nomor sertifikat atau nama untuk mencari',
    'error.search.failed': 'Pencarian gagal. Silakan coba lagi.',
    
    // Login Modal
    'login.welcomeBack': 'Selamat Datang Kembali',
    'login.signInMessage': 'Masuk ke akun Anda untuk melanjutkan',
    'login.emailAddress': 'Alamat Email',
    'login.password': 'Kata Sandi',
    'login.enterEmail': 'Masukkan email Anda',
    'login.enterPassword': 'Masukkan kata sandi Anda',
    'login.signIn': 'Masuk',
    'login.signingIn': 'Sedang masuk...',
    'login.orContinueWith': 'Atau lanjutkan dengan',
    
    // Auth Callback
    'auth.callback.finishingSignIn': 'Menyelesaikan masuk…',
    'auth.callback.signingYouIn': 'Memproses masuk Anda…',
    'auth.callback.finalisingSession': 'Menyelesaikan sesi…',
    'auth.callback.settingUpAccount': 'Menyiapkan akun Anda…',
    'auth.callback.almostDone': 'Hampir selesai…',
    'auth.callback.success': 'Login berhasil! Mengarahkan…',
    'auth.callback.authFailed': 'Autentikasi gagal. Mengarahkan ke beranda…',
    'auth.callback.authFailedShort': 'Autentikasi gagal. Mengarahkan…',
    'auth.callback.noSession': 'Sesi tidak ditemukan. Mengarahkan…',
    'auth.callback.errorOccurred': 'Terjadi kesalahan. Mengarahkan…',
    'auth.callback.takeMeHome': 'Bawa saya ke beranda',
    
    // Error Messages - Login
    'error.login.invalidEmail': 'Silakan masukkan alamat email yang valid.',
    'error.login.invalidPassword': 'Kata sandi Anda harus minimal 6 karakter.',
    'error.login.invalidCredentials': 'Email atau kata sandi salah.',
    
    // Search & Filter
    'search.category': 'Kategori',
    'search.allCategories': 'Semua Kategori',
    'search.dateRange': 'Rentang Tanggal',
    'search.startDate': 'Tanggal Mulai',
    'search.endDate': 'Tanggal Akhir',
    'search.clearFilters': 'Hapus Filter',
    'search.noResults': 'Tidak ada hasil yang cocok untuk',
    'search.noResultsGeneral': 'Tidak ada sertifikat ditemukan',
    'search.filteredBy': 'Difilter berdasarkan',
    'search.showingResults': 'Menampilkan hasil',
    'search.foundFor': 'ditemukan untuk',
    'search.searchByName': 'Cari berdasarkan nama atau nomor sertifikat...',
    'search.inCategory': 'di kategori',
    'search.found': 'ditemukan',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      try {
        const saved = window.localStorage.getItem('ecert-language');
        if (saved === 'en' || saved === 'id') return saved;
      } catch {}
    }
    return 'en';
  });

  // removed unused hydrated state

  useEffect(() => {
    try {
      if (typeof window !== 'undefined') {
        window.localStorage.setItem('ecert-language', language);
      }
    } catch {}
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
