"use client";

import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
type Translations = Record<Language, Record<string, string>>;
const translations: Translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.templates': 'Templates',
    'nav.certificates': 'Certificates',
    'nav.myCertificates': 'My Certificates',
    'nav.faq': 'FAQ',
    'nav.management': 'Management',
    'nav.explore': 'Explore',
    'nav.contact': 'Contact',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Log Out',
    'auth.role': 'Role',
    'auth.selectRole': 'Select Role',
    'auth.admin': 'Admin',
    'auth.team': 'Team',
    'auth.public': 'Public',
    
    // Templates
    'templates.title': 'Templates',
    'templates.subtitle': 'Manage and create certificate templates',
    'templates.create': 'Create Template',
    'templates.edit': 'Edit',
    'templates.delete': 'Delete',
    'templates.preview': 'Preview',
    'templates.name': 'Template Name',
    'templates.category': 'Category',
    'templates.orientation': 'Orientation',
    'templates.landscape': 'Landscape',
    'templates.portrait': 'Portrait',
    'templates.description': 'Description',
    'templates.actions': 'Actions',
    'templates.search': 'Search templates...',
    'templates.allCategories': 'All Categories',
    'templates.noTemplates': 'No templates found',
    'templates.createNew': 'Create New Template',
    'templates.templatePreview': 'Template Preview',
    'templates.templateDetails': 'Details and preview of the selected template.',
    'templates.cleanupImages': 'Cleanup Images',
    'templates.cleaning': 'Cleaning...',
    'templates.useThisTemplate': 'Use This Template',
    'templates.loading': 'Loading Templates',
    
    // Certificates
    'certificates.title': 'Certificates',
    'certificates.subtitle': 'Manage and track certificates',
    'certificates.create': 'Create Certificate',
    'certificates.certificateId': 'Certificate Number',
    'certificates.recipient': 'Recipient',
    'certificates.issuedDate': 'Issued Date',
    'certificates.expiryDate': 'Expiry Date',
    'certificates.status': 'Status',
    'certificates.actions': 'Actions',
    'certificates.search': 'Search certificates...',
    'certificates.noCertificates': 'No certificates found',
    'certificates.download': 'Download',
    'certificates.verify': 'Verify',
    'certificates.edit': 'Edit',
    'certificates.delete': 'Delete',
    'certificates.category': 'Category',
    'certificates.description': 'Description',
    'certificates.updateSuccess': 'Certificate updated successfully!',
    'certificates.updateFailed': 'Failed to update certificate',
    'certificates.deleteNoPermission': "You don't have permission to delete certificates",
    'certificates.deleteConfirm': 'Are you sure you want to delete certificate for "{name}"?\n\nCertificate Number: {number}\n\nThis action cannot be undone.',
    'certificates.deleteSuccess': 'Certificate for "{name}" deleted successfully!',
    'certificates.deleteFailed': 'Failed to delete certificate. Please try again.',
    'certificates.deleting': 'Deleting...',
    'certificates.loading': 'Loading certificates...',
    'certificates.loadingMessage': 'Please wait while we fetch your certificates.',
    'certificates.errorLoading': 'Error loading certificates',
    'certificates.tryAgain': 'Try Again',
    'certificates.filterByDate': 'Filter by date',
    'certificates.export': 'Export',
    'certificates.exportPdf': 'Export as PDF',
    'certificates.downloadPng': 'Download PNG',
    'certificates.sendEmail': 'Send via Email',
    'certificates.generateLink': 'Generate Certificate Link',
    'certificates.showing': 'Showing {start}-{end} of {total} certificates',
    'certificates.filteredFrom': '(filtered from {total})',
    'certificates.previous': 'Previous',
    'certificates.next': 'Next',
    'certificates.page': 'Page {current} of {total}',
    'certificates.noCertificatesMessage': 'Try adjusting your search criteria or create a new certificate.',
    'certificates.updateDetails': 'Update certificate details.',
    'certificates.selectCategory': 'Select category',
    'certificates.preview': 'Certificate Preview',
    'certificates.previewDescription': 'View certificate details and information',
    'certificates.certificateTitle': 'CERTIFICATE',
    'certificates.certifyText': 'This is to certify that',
    'certificates.completedText': 'has successfully completed the',
    'certificates.certificateNo': 'Certificate No:',
    'certificates.issueDate': 'Issue Date:',
    'certificates.fallbackPreview': 'This is a fallback preview. Configure template text layers for a fully customized certificate design.',
    'certificates.memberInfoNotAvailable': 'Member information not available',
    'certificates.loadMemberDetailsFailed': 'Failed to load member details',
    'certificates.generate': 'Generate',
    'certificates.viewCertificates': 'View Certificates',
    'certificates.saveSuccessWithScore': 'Certificate and Score saved successfully! Would you like to view all certificates?',
    'certificates.saveSuccess': 'Certificate saved successfully! Would you like to view all certificates?',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.preview': 'Preview',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    
    // Footer
    'footer.multilingual': 'Multilingual Platform',
    'footer.phone': '+6281380935185',
    'footer.email': 'fahrirafa.rpl1@gmail.com',
    'footer.location': 'Malang',
    
    // Language
    'language.english': 'English',
    'language.indonesia': 'Indonesia',
    'language.switch': 'Switch Language',
    
    // Theme
    'theme.switch': 'Switch Theme',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    
    // Hero Section
    'hero.title': 'Search Certificate',
    'hero.subtitle': 'Digital Certificate Solutions',
    'hero.description': 'Create, manage, and verify digital certificates for trainings, internships, MoUs, and industrial visits with our professional multilingual platform.',
    'hero.searchPlaceholder': 'Search certificate by ID...',
    'hero.searchButton': 'Search',
    'hero.searching': 'Searching...',
    'hero.getStarted': 'Get Started',
    'hero.learnMore': 'Learn More',
    'hero.certificatePreview': 'Certificate Preview',
    'hero.close': 'Close',
    'hero.recipient': 'Name',
    'hero.category': 'Category',
    'hero.template': 'Template',
    'hero.issued': 'Issued',
    'hero.expires': 'Expires',
    'hero.noPreviewImage': 'No preview image',
    'hero.certificate': 'certificate',
    'hero.certificates': 'certificates',
    'hero.viewFullImage': 'Click to view full image',
    'hero.export': 'Export',
    'hero.exportAsPDF': 'Export as PDF',
    'hero.downloadPNG': 'Download PNG',
    'hero.sendViaEmail': 'Send via Email',
    'hero.imageNotAvailable': 'Certificate image not available to export',
    'hero.pdfLibraryMissing': 'PDF library missing. Please install \'jspdf\' dependency.',
    'hero.pdfExported': 'PDF exported',
    'hero.pngDownloaded': 'PNG downloaded successfully',
    'hero.noPublicLink': 'Certificate does not have a public link ID',
    'hero.linkCopied': 'Public certificate link copied',
    'hero.linkGenerateFailed': 'Failed to generate certificate link',
    'hero.imageNotAvailableShort': 'Certificate image not available',
    'hero.emailQueued': 'Email queued successfully! Preview opened in new tab',
    'hero.loadCategoriesFailed': 'Failed to load categories',
    'hero.generateLink': 'Generate Certificate Link',
    'hero.certificateImage': 'Certificate Image',
    'hero.sendEmailTitle': 'Send Certificate via Email',
    'hero.sendEmailSubtitle': 'Configure email details',
    'hero.certificatePreviewLabel': 'Certificate Preview:',
    'hero.recipientEmail': 'Recipient Email',
    'hero.subject': 'Subject',
    'hero.message': 'Message',
    'hero.emailSubjectPlaceholder': 'Email subject',
    'hero.emailMessagePlaceholder': 'Email message',
    'hero.cancel': 'Cancel',
    'hero.sendEmail': 'Send Email',
    'hero.sending': 'Sending...',
    
    // About Section
    'about.title': 'About',
    'about.description1': 'Our multilingual E-Certificate Management Platform revolutionizes how organizations create, manage, and verify certificates for various programs including trainings, internships, MoUs, and industrial visits.',
    'about.description2': 'Built with modern technology stack including Next.js, Shadcn UI, Tailwind CSS, and Supabase, our platform ensures scalability, security, and seamless user experience across multiple languages.',
    'about.features.multiUser': 'Multi-User Management',
    'about.features.multiUserDesc': 'Support for Admin, Team, and Public access levels with role-based permissions.',
    'about.features.professional': 'Professional Certificates',
    'about.features.professionalDesc': 'Create beautiful, verifiable certificates with customizable templates and layouts.',
    'about.features.secure': 'Secure Verification',
    'about.features.secureDesc': 'Public verification system with unique URLs for each certificate.',
    'about.features.email': 'Email Integration',
    'about.features.emailDesc': 'Send certificates via email individually or in bulk with advanced filtering options.',
    
    // Footer
    'footer.quickLinks': 'Quick Links',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact Us',
    'footer.cookies': 'Cookie Policy',
    'footer.developedBy': 'Developed by',
    
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about our platform',
    'faq.q1': 'What is the E-Certificate Management Platform?',
    'faq.a1': 'The E-Certificate Management Platform is a comprehensive solution for creating, managing, and verifying certificates for various programs including trainings, internships, MoUs, and industrial visits. It supports multiple languages and offers role-based access control.',
    'faq.q2': 'What languages are supported?',
    'faq.a2': 'Our platform currently supports English (default) and Indonesian languages, with seamless switching between them. We\'re continuously working to add more language support based on user demand.',
    'faq.q3': 'What are the different access levels?',
    'faq.a3': 'We offer three main access levels: Admin (full management access), Team (can add, view, and edit certificates but cannot delete), and Public (can search and view specific certificates via search or direct URL access).',
    'faq.q4': 'How do I create a certificate?',
    'faq.a4': 'Creating certificates is simple: 1) Choose or create a template, 2) Select a category, 3) Add member information, 4) Generate the certificate as PDF, and 5) Send via email if needed. Our platform guides you through each step.',
    'faq.q5': 'Can I import data from Excel?',
    'faq.a5': 'Yes, our platform supports bulk import from Excel files. You can upload a spreadsheet with member information and automatically generate multiple certificates at once.',
    'faq.q6': 'How secure are the certificates?',
    'faq.a6': 'All certificates are secured with unique verification URLs and can be verified publicly. We use industry-standard encryption and security measures to protect your data.',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Platform preferences',
    'settings.organization': 'Organization Name',
    'settings.organizationPlaceholder': 'Your organization',
    'settings.language': 'Default Language',
    'settings.languagePlaceholder': 'en / id',
    'settings.save': 'Save Changes',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome to your dashboard',
    'dashboard.overview': 'Overview',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.stats.members': 'Members',
    'dashboard.stats.membersChange': '+5 this week',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Platform usage and insights',
    'analytics.totalCertificates': 'Total Certificates',
    'analytics.totalTemplates': 'Total Templates',
    'analytics.totalUsers': 'Total Users',
    'analytics.recentActivity': 'Recent Activity',
    'analytics.keyStatistics': 'Key Statistics',
    'analytics.certificatesIssued': 'Certificates Issued',
    'analytics.templatesAvailable': 'Templates Available',
    'analytics.registeredMembers': 'Registered Members',
    'analytics.certificateCategories': 'Certificate Categories',
    
    // Categories
    'categories.title': 'Categories',
    'categories.subtitle': 'Manage certificate categories',
    'categories.create': 'Create Category',
    'categories.name': 'Category Name',
    'categories.description': 'Description',
    'categories.color': 'Color',
    'categories.actions': 'Actions',
    
    // Members
    'members.title': 'Members',
    'members.subtitle': 'Manage members and their certificates',
    'members.addMember': 'Add Member',
    'members.viewCertificates': 'View Certificates',
    'members.loadCertificatesFailed': 'Failed to load certificates',
    'members.loadMembersFailed': 'Failed to load members',
    'members.loadingPage': 'Preparing members page...',
    'members.accessDenied.title': 'Access Denied',
    'members.accessDenied.message': 'You do not have permission to view this page.',
    'members.nameRequired': 'Full name is required',
    'members.updateSuccess': 'Member updated successfully',
    'members.updateFailed': 'Failed to update member',
    'members.addSuccess': 'Member added successfully',
    'members.addFailed': 'Failed to add member',
    'members.deleteNoPermission': "You don't have permission to delete members",
    'members.deleteSuccess': 'Member deleted successfully',
    'members.deleteFailed': 'Failed to delete member',
    'members.adding': 'Adding...',
    'members.saving': 'Saving...',
    'members.saveChanges': 'Save Changes',
    'members.certificateImagePreview': 'Certificate Image',
    'members.noImage': 'No image',
    'members.loadingMembers': 'Loading members...',
    'members.noMembersTitle': 'No members yet',
    'members.noMembersMessage': 'Start by adding your first member.',
    'members.certificates': 'Certificates',
    'members.noCertificatesForMember': 'No certificates for this member',
    'members.editMember': 'Edit Member',
    'members.form.fullName': 'Full Name',
    'members.form.fullNamePlaceholder': 'e.g. John Doe',
    'members.form.email': 'Email',
    'members.form.organization': 'Organization',
    'members.form.phone': 'Phone',
    'members.form.job': 'Job',
    'members.form.dob': 'Date of Birth',
    'members.form.address': 'Address',
    'members.form.city': 'City',
    'members.form.notes': 'Notes',
    'members.form.optional': 'Optional',
    'members.table.name': 'Name',
    'members.table.organization': 'Organization',
    'members.table.email': 'Email',
    'members.table.phone': 'Phone',
    'members.table.contact': 'Contact',
    'members.excel.title': 'Excel Import Format',
    'members.excel.description': 'Please prepare your Excel file with the following columns',
    'members.excel.requiredColumns': 'Required Columns:',
    'members.excel.optionalColumns': 'Columns To Fill:',
    'members.excel.exampleFormat': 'Example Format:',
    'members.excel.note': 'Note:',
    'members.excel.noteText': 'Column names are case-insensitive. You can use "Name", "name", or "NAME".',
    'members.excel.cancel': 'Cancel',
    'members.excel.chooseFile': 'Choose Excel File',
    'members.excel.importing': 'Importing...',
    'members.excel.importExcel': 'Import Excel',
    'members.excel.nameRequired': 'Full name of the member (Required)',
    'members.table.job': 'Job',
    'members.table.city': 'City',
    'members.table.actions': 'Actions',
    'members.search.noResults': 'No members found',
    'members.search.noMatch': 'No members match your search',
    'members.search.clearSearch': 'Clear search',
    'members.detail.title': 'Member Information',
    'members.detail.description': 'Detailed information about',

    // My Certificates
    'myCertificates.title': 'My Certificates',
    'myCertificates.subtitle': 'View and manage your certificates',
    'myCertificates.search': 'Search certificates...',
    'myCertificates.noCertificates': 'No certificates found',
    'myCertificates.download': 'Download',
    'myCertificates.verify': 'Verify',
    
    // Certificate Generator
    'generator.title': 'Certificate Generator',
    'generator.subtitle': 'Create and customize certificates',
    'generator.template': 'Template',
    'generator.recipient': 'Recipient Information',
    'generator.preview': 'Certificate Preview',
    'generator.generate': 'Generate Certificate',
    'generator.download': 'Download PDF',
    'generator.email': 'Send via Email',
    'generator.recipientName': 'Recipient Name',
    'generator.recipientEmail': 'Recipient Email',
    'generator.courseName': 'Course Name',
    'generator.completionDate': 'Completion Date',
    'generator.certificateId': 'Certificate ID',
    'generator.organization': 'Organization',
    'generator.instructor': 'Instructor',
    'generator.duration': 'Duration',
    'generator.grade': 'Grade',
    'generator.notes': 'Notes',
    
    // Quick Generate Modal
    'quickGenerate.title': 'Generate Certificate',
    'quickGenerate.description': 'Generate certificates by selecting a template and data source',
    'quickGenerate.selectTemplate': 'Select Template',
    'quickGenerate.chooseTemplate': 'Choose a template...',
    'quickGenerate.loadingTemplates': 'Loading templates...',
    'quickGenerate.notConfigured': 'Not Configured',
    'quickGenerate.dataSource': 'Data Source',
    'quickGenerate.selectMember': 'Select Member',
    'quickGenerate.selectMembers': 'Select Member(s)',
    'quickGenerate.uploadExcel': 'Upload Excel',
    'quickGenerate.loadingMembers': 'Loading members...',
    'quickGenerate.noOrganization': 'No Organization',
    'quickGenerate.membersSelected': 'member(s) selected',
    'quickGenerate.dateFormat': 'Date Format',
    'quickGenerate.issueDate': 'Issue Date',
    'quickGenerate.expiredDate': 'Expired Date',
    'quickGenerate.chooseExcelFile': 'Choose Excel File',
    'quickGenerate.uploadExcelHint': 'Upload .xlsx or .xls file',
    'quickGenerate.rowsLoaded': 'rows loaded',
    'quickGenerate.willGenerate': 'This will generate',
    'quickGenerate.certificatesAtOnce': 'certificate(s) at once',
    'quickGenerate.cancel': 'Cancel',
    'quickGenerate.generating': 'Generating...',
    'quickGenerate.generate': 'Generate',
    'quickGenerate.selectTemplateError': 'Please select a template',
    'quickGenerate.selectMemberError': 'Please select at least one member',
    'quickGenerate.uploadExcelError': 'Please upload Excel file',
    'quickGenerate.generateError': 'Failed to generate certificate',
    'quickGenerate.loadedRows': 'Loaded',
    'quickGenerate.rowsFromExcel': 'rows from Excel',
    'quickGenerate.parseExcelError': 'Failed to parse Excel file',
    'quickGenerate.generatingCertificates': 'Generating certificates...',
    'quickGenerate.successSingle': 'Certificate generated successfully!',
    'quickGenerate.successMultiple': 'Successfully generated',
    'quickGenerate.certificatesGenerated': 'certificate(s)!',
    
    // Navigation
    'nav.menu': 'Menu',
    
    // Error Messages - Search
    'error.search.notFound': 'Certificate not found. Please check the certificate number or link and try again.',
    'error.search.empty': 'Please enter a certificate number or name to search',
    'error.search.failed': 'Search failed. Please try again.',
    
    // Login Modal
    'login.welcomeBack': 'Welcome Back',
    'login.signInMessage': 'Sign in to your account to continue',
    'login.emailAddress': 'Email Address',
    'login.password': 'Password',
    'login.enterEmail': 'Enter your email',
    'login.enterPassword': 'Enter your password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.orContinueWith': 'Or continue with',
    
    // Auth Callback
    'auth.callback.finishingSignIn': 'Finishing sign in…',
    'auth.callback.signingYouIn': 'Signing you in…',
    'auth.callback.finalisingSession': 'Finalising session…',
    'auth.callback.settingUpAccount': 'Setting up your account…',
    'auth.callback.almostDone': 'Almost done…',
    'auth.callback.success': 'Login successful! Redirecting…',
    'auth.callback.authFailed': 'Authentication failed. Redirecting to home…',
    'auth.callback.authFailedShort': 'Authentication failed. Redirecting…',
    'auth.callback.noSession': 'No session found. Redirecting…',
    'auth.callback.errorOccurred': 'An error occurred. Redirecting…',
    'auth.callback.takeMeHome': 'Take me home',
    
    // Error Messages - Login
    'error.login.invalidEmail': 'Please enter a valid email address.',
    'error.login.invalidPassword': 'Your password must be at least 6 characters long.',
    'error.login.invalidCredentials': 'Invalid email or password.',
    
    // Search & Filter
    'search.filters': 'Filters',
    'search.category': 'Category',
    'search.allCategories': 'All Categories',
    'search.dateRange': 'Date Range',
    'search.startDate': 'Start Date',
    'search.endDate': 'End Date',
    'search.clearFilters': 'Clear Filters',
    'search.applyFilters': 'Apply Filters',
    'search.noResults': 'No matching results found for',
    'search.noResultsGeneral': 'No certificates found',
    'search.filteredBy': 'Filtered by',
    'search.showingResults': 'Showing results',
    'search.searchByName': 'Search by name or number...',
  },
  id: {
    // Navigation
    'nav.home': 'Beranda',
    'nav.about': 'Tentang E-Certificate',
    'nav.templates': 'Template',
    'nav.certificates': 'Sertifikat',
    'nav.myCertificates': 'Sertifikat Saya',
    'nav.faq': 'FAQ',
    'nav.management': 'Manajemen',
    'nav.explore': 'Jelajahi',
    'nav.contact': 'Kontak',
    
    // Auth
    'auth.login': 'Masuk',
    'auth.register': 'Daftar',
    'auth.logout': 'Keluar',
    'auth.role': 'Peran',
    'auth.selectRole': 'Pilih Peran',
    'auth.admin': 'Admin',
    'auth.team': 'Tim',
    'auth.public': 'Publik',
    
    // Templates
    'templates.title': 'Template',
    'templates.subtitle': 'Kelola dan buat template sertifikat',
    'templates.create': 'Buat Template',
    'templates.edit': 'Edit',
    'templates.delete': 'Hapus',
    'templates.preview': 'Pratinjau',
    'templates.name': 'Nama Template',
    'templates.category': 'Kategori',
    'templates.orientation': 'Orientasi',
    'templates.landscape': 'Landscape',
    'templates.portrait': 'Portrait',
    'templates.description': 'Deskripsi',
    'templates.actions': 'Aksi',
    'templates.search': 'Cari template...',
    'templates.allCategories': 'Semua Kategori',
    'templates.noTemplates': 'Tidak ada template ditemukan',
    'templates.createNew': 'Buat Template Baru',
    'templates.templatePreview': 'Pratinjau Template',
    'templates.templateDetails': 'Detail dan pratinjau template yang dipilih.',
    'templates.cleanupImages': 'Bersihkan Gambar',
    'templates.cleaning': 'Membersihkan...',
    'templates.useThisTemplate': 'Gunakan Template Ini',
    'templates.loading': 'Memuat Template',
    
    // Certificates
    'certificates.title': 'Sertifikat',
    'certificates.subtitle': 'Kelola dan lacak sertifikat',
    'certificates.create': 'Buat Sertifikat',
    'certificates.certificateId': 'Nomor Sertifikat',
    'certificates.recipient': 'Penerima',
    'certificates.issuedDate': 'Tanggal Diterbitkan',
    'certificates.expiryDate': 'Tanggal Kedaluwarsa',
    'certificates.status': 'Status',
    'certificates.actions': 'Aksi',
    'certificates.search': 'Cari sertifikat...',
    'certificates.noCertificates': 'Tidak ada sertifikat ditemukan',
    'certificates.category': 'Kategori',
    'certificates.description': 'Deskripsi',
    'certificates.updateSuccess': 'Sertifikat berhasil diperbarui!',
    'certificates.updateFailed': 'Gagal memperbarui sertifikat',
    'certificates.deleteNoPermission': 'Anda tidak memiliki izin untuk menghapus sertifikat',
    'certificates.deleteConfirm': 'Apakah Anda yakin ingin menghapus sertifikat untuk "{name}"?\n\nNomor Sertifikat: {number}\n\nTindakan ini tidak dapat dibatalkan.',
    'certificates.deleteSuccess': 'Sertifikat untuk "{name}" berhasil dihapus!',
    'certificates.deleteFailed': 'Gagal menghapus sertifikat. Silakan coba lagi.',
    'certificates.deleting': 'Menghapus...',
    'certificates.loading': 'Memuat sertifikat...',
    'certificates.loadingMessage': 'Mohon tunggu sementara kami mengambil sertifikat Anda.',
    'certificates.errorLoading': 'Error memuat sertifikat',
    'certificates.tryAgain': 'Coba Lagi',
    'certificates.filterByDate': 'Filter berdasarkan tanggal',
    'certificates.export': 'Ekspor',
    'certificates.exportPdf': 'Ekspor sebagai PDF',
    'certificates.downloadPng': 'Unduh PNG',
    'certificates.sendEmail': 'Kirim via Email',
    'certificates.generateLink': 'Buat Link Sertifikat',
    'certificates.showing': 'Menampilkan {start}-{end} dari {total} sertifikat',
    'certificates.filteredFrom': '(difilter dari {total})',
    'certificates.previous': 'Sebelumnya',
    'certificates.next': 'Selanjutnya',
    'certificates.page': 'Halaman {current} dari {total}',
    'certificates.noCertificatesMessage': 'Coba sesuaikan kriteria pencarian Anda atau buat sertifikat baru.',
    'certificates.updateDetails': 'Perbarui detail sertifikat.',
    'certificates.selectCategory': 'Pilih kategori',
    'certificates.preview': 'Pratinjau Sertifikat',
    'certificates.previewDescription': 'Lihat detail dan informasi sertifikat',
    'certificates.certificateTitle': 'SERTIFIKAT',
    'certificates.certifyText': 'Ini untuk menyatakan bahwa',
    'certificates.completedText': 'telah berhasil menyelesaikan',
    'certificates.certificateNo': 'Nomor Sertifikat:',
    'certificates.issueDate': 'Tanggal Terbit:',
    'certificates.fallbackPreview': 'Ini adalah pratinjau fallback. Konfigurasi template text layers untuk desain sertifikat yang sepenuhnya disesuaikan.',
    'certificates.memberInfoNotAvailable': 'Informasi anggota tidak tersedia',
    'certificates.loadMemberDetailsFailed': 'Gagal memuat detail anggota',
    'certificates.generate': 'Generate',
    'certificates.viewCertificates': 'Lihat Sertifikat',
    'certificates.saveSuccessWithScore': 'Sertifikat dan Nilai berhasil disimpan! Apakah Anda ingin melihat semua sertifikat?',
    'certificates.saveSuccess': 'Sertifikat berhasil disimpan! Apakah Anda ingin melihat semua sertifikat?',
    
    // Common
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.close': 'Tutup',
    'common.edit': 'Edit',
    'common.delete': 'Hapus',
    'common.preview': 'Pratinjau',
    'common.search': 'Cari',
    'common.loading': 'Memuat...',
    'common.error': 'Error',
    'common.success': 'Berhasil',
    'common.confirm': 'Konfirmasi',
    'common.yes': 'Ya',
    'common.no': 'Tidak',
    
    // Footer
    'footer.multilingual': 'Platform Multibahasa',
    'footer.phone': '+6281380935185',
    'footer.email': 'fahrirafa.rpl1@gmail.com',
    'footer.location': 'Malang',
    
    // Language
    'language.english': 'English',
    'language.indonesia': 'Indonesia',
    'language.switch': 'Ganti Bahasa',
    
    // Theme
    'theme.switch': 'Ganti Tema',
    'theme.light': 'Terang',
    'theme.dark': 'Gelap',
    
    // Hero Section
    'hero.title': 'Cari Sertifikat',
    'hero.subtitle': 'Solusi Sertifikat Digital',
    'hero.description': 'Buat, kelola, dan verifikasi sertifikat digital untuk pelatihan, magang, MoU, dan kunjungan industri dengan platform multibahasa profesional kami.',
    'hero.searchPlaceholder': 'Cari sertifikat berdasarkan ID...',
    'hero.searchButton': 'Cari',
    'hero.searching': 'Mencari...',
    'hero.learnMore': 'Pelajari Lebih Lanjut',
    'hero.certificatePreview': 'Pratinjau Sertifikat',
    'hero.close': 'Tutup',
    'hero.recipient': 'Nama',
    'hero.category': 'Kategori',
    'hero.template': 'Template',
    'hero.issued': 'Diterbitkan',
    'hero.expires': 'Kadaluarsa',
    'hero.noPreviewImage': 'Tidak ada gambar pratinjau',
    'hero.certificate': 'sertifikat',
    'hero.certificates': 'sertifikat',
    'hero.viewFullImage': 'Klik untuk melihat penuh',
    'hero.export': 'Ekspor',
    'hero.exportAsPDF': 'Ekspor sebagai PDF',
    'hero.downloadPNG': 'Unduh PNG',
    'hero.sendViaEmail': 'Kirim via Email',
    'hero.imageNotAvailable': 'Gambar sertifikat tidak tersedia untuk diekspor',
    'hero.pdfLibraryMissing': 'Library PDF tidak ditemukan. Silakan install dependensi \'jspdf\'.',
    'hero.pdfExported': 'PDF berhasil diekspor',
    'hero.pngDownloaded': 'PNG berhasil diunduh',
    'hero.noPublicLink': 'Sertifikat tidak memiliki ID link publik',
    'hero.linkCopied': 'Link sertifikat publik disalin',
    'hero.linkGenerateFailed': 'Gagal membuat link sertifikat',
    'hero.imageNotAvailableShort': 'Gambar sertifikat tidak tersedia',
    'hero.emailQueued': 'Email berhasil diantrekan! Pratinjau dibuka di tab baru',
    'hero.loadCategoriesFailed': 'Gagal memuat kategori',
    'hero.generateLink': 'Buat Link Sertifikat',
    'hero.certificateImage': 'Gambar Sertifikat',
    'hero.sendEmailTitle': 'Kirim Sertifikat via Email',
    'hero.sendEmailSubtitle': 'Konfigurasi detail email',
    'hero.certificatePreviewLabel': 'Pratinjau Sertifikat:',
    'hero.recipientEmail': 'Email Penerima',
    'hero.subject': 'Subjek',
    'hero.message': 'Pesan',
    'hero.emailSubjectPlaceholder': 'Subjek email',
    'hero.emailMessagePlaceholder': 'Pesan email',
    'hero.cancel': 'Batal',
    'hero.sendEmail': 'Kirim Email',
    'hero.sending': 'Mengirim...',
    
    // About Section
    'about.title': 'Tentang E-Certificate',
    'about.description1': 'Platform Manajemen E-Certificate multibahasa kami merevolusi cara organisasi membuat, mengelola, dan memverifikasi sertifikat untuk berbagai program termasuk pelatihan, magang, MoU, dan kunjungan industri.',
    'about.description2': 'Dibangun dengan teknologi modern termasuk Next.js, Shadcn UI, Tailwind CSS, dan Supabase, platform kami memastikan skalabilitas, keamanan, dan pengalaman pengguna yang mulus di berbagai bahasa.',
    'about.features.multiUser': 'Manajemen Multi-Pengguna',
    'about.features.multiUserDesc': 'Dukungan untuk level akses Admin, Tim, dan Publik dengan izin berbasis peran.',
    'about.features.professional': 'Sertifikat Profesional',
    'about.features.professionalDesc': 'Buat sertifikat yang indah dan dapat diverifikasi dengan template dan tata letak yang dapat disesuaikan.',
    'about.features.secure': 'Verifikasi Aman',
    'about.features.secureDesc': 'Sistem verifikasi publik dengan URL unik untuk setiap sertifikat.',
    'about.features.email': 'Integrasi Email',
    'about.features.emailDesc': 'Kirim sertifikat melalui email secara individual atau massal dengan opsi filter lanjutan.',
    
    // Footer
    'footer.quickLinks': 'Tautan Cepat',
    'footer.legal': 'Legal',
    'footer.privacy': 'Kebijakan Privasi',
    'footer.terms': 'Syarat Layanan',
    'footer.contact': 'Hubungi Kami',
    'footer.cookies': 'Kebijakan Cookie',
    'footer.developedBy': 'Dikembangkan oleh',
    
    
    // FAQ
    'faq.title': 'Pertanyaan yang Sering Diajukan',
    'faq.subtitle': 'Temukan jawaban untuk pertanyaan umum tentang platform kami',
    'faq.q1': 'Apa itu Platform Manajemen E-Certificate?',
    'faq.a1': 'Platform Manajemen E-Certificate adalah solusi komprehensif untuk membuat, mengelola, dan memverifikasi sertifikat untuk berbagai program termasuk pelatihan, magang, MoU, dan kunjungan industri. Mendukung berbagai bahasa dan menawarkan kontrol akses berbasis peran.',
    'faq.q2': 'Bahasa apa saja yang didukung?',
    'faq.a2': 'Platform kami saat ini mendukung bahasa Inggris (default) dan Indonesia, dengan peralihan yang mulus di antara keduanya. Kami terus bekerja untuk menambahkan dukungan bahasa lebih banyak berdasarkan permintaan pengguna.',
    'faq.q3': 'Apa saja level akses yang berbeda?',
    'faq.a3': 'Kami menawarkan tiga level akses utama: Admin (akses manajemen penuh), Tim (dapat menambah, melihat, dan mengedit sertifikat tetapi tidak dapat menghapus), dan Publik (dapat mencari dan melihat sertifikat tertentu melalui pencarian atau akses URL langsung).',
    'faq.q4': 'Bagaimana cara membuat sertifikat?',
    'faq.a4': 'Membuat sertifikat sangat mudah: 1) Pilih atau buat template, 2) Pilih kategori, 3) Tambahkan informasi anggota, 4) Generate sertifikat sebagai PDF, dan 5) Kirim melalui email jika diperlukan. Platform kami memandu Anda melalui setiap langkah.',
    'faq.q5': 'Bisakah saya mengimpor data dari Excel?',
    'faq.a5': 'Ya, platform kami mendukung impor massal dari file Excel. Anda dapat mengunggah spreadsheet dengan informasi anggota dan secara otomatis menghasilkan beberapa sertifikat sekaligus.',
    'faq.q6': 'Seberapa aman sertifikat-sertifikat tersebut?',
    'faq.a6': 'Semua sertifikat diamankan dengan URL verifikasi unik dan dapat diverifikasi secara publik. Kami menggunakan enkripsi standar industri dan langkah-langkah keamanan untuk melindungi data Anda.',
    
    // Settings
    'settings.title': 'Pengaturan',
    'settings.subtitle': 'Preferensi platform',
    'settings.organization': 'Nama Organisasi',
    'settings.organizationPlaceholder': 'Organisasi Anda',
    'settings.language': 'Bahasa Default',
    'settings.languagePlaceholder': 'en / id',
    'settings.save': 'Simpan Perubahan',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Selamat datang di dashboard Anda',
    'dashboard.overview': 'Ringkasan',
    'dashboard.recentActivity': 'Aktivitas Terbaru',
    'dashboard.quickActions': 'Aksi Cepat',
    
    // Analytics
    'analytics.title': 'Analitik',
    'analytics.subtitle': 'Penggunaan platform dan wawasan',
    'analytics.totalCertificates': 'Total Sertifikat',
    'analytics.totalTemplates': 'Total Template',
    'analytics.totalUsers': 'Total Pengguna',
    'analytics.recentActivity': 'Aktivitas Terbaru',
    'analytics.keyStatistics': 'Statistik Utama',
    'analytics.certificatesIssued': 'Sertifikat Diterbitkan',
    'analytics.templatesAvailable': 'Template Tersedia',
    'analytics.registeredMembers': 'Anggota Terdaftar',
    'analytics.certificateCategories': 'Kategori Sertifikat',
    
    // Categories
    'categories.title': 'Kategori',
    'categories.subtitle': 'Kelola kategori sertifikat',
    'categories.create': 'Buat Kategori',
    'categories.name': 'Nama Kategori',
    'categories.description': 'Deskripsi',
    'categories.color': 'Warna',
    'categories.actions': 'Aksi',
    
    // Members
    'members.title': 'Anggota',
    'members.subtitle': 'Kelola anggota dan sertifikatnya',
    'members.addMember': 'Tambah Anggota',
    'members.viewCertificates': 'Lihat Sertifikat',
    'members.loadCertificatesFailed': 'Gagal memuat sertifikat',
    'members.loadMembersFailed': 'Gagal memuat data anggota',
    'members.loadingPage': 'Menyiapkan halaman anggota...',
    'members.accessDenied.title': 'Akses Ditolak',
    'members.accessDenied.message': 'Anda tidak memiliki izin untuk melihat halaman ini.',
    'members.nameRequired': 'Nama lengkap wajib diisi',
    'members.updateSuccess': 'Data anggota berhasil diperbarui',
    'members.updateFailed': 'Gagal memperbarui data anggota',
    'members.addSuccess': 'Anggota berhasil ditambahkan',
    'members.addFailed': 'Gagal menambahkan anggota',
    'members.deleteNoPermission': 'Anda tidak memiliki izin untuk menghapus anggota',
    'members.deleteSuccess': 'Anggota berhasil dihapus',
    'members.deleteFailed': 'Gagal menghapus anggota',
    'members.adding': 'Menambahkan...',
    'members.saving': 'Menyimpan...',
    'members.saveChanges': 'Simpan Perubahan',
    'members.certificateImagePreview': 'Gambar Sertifikat',
    'members.noImage': 'Tidak ada gambar',
    'members.loadingMembers': 'Memuat data anggota...',
    'members.noMembersTitle': 'Belum ada anggota',
    'members.noMembersMessage': 'Mulai dengan menambahkan anggota pertama Anda.',
    'members.certificates': 'Sertifikat',
    'members.noCertificatesForMember': 'Tidak ada sertifikat untuk anggota ini',
    'members.editMember': 'Edit Anggota',
    'members.form.fullName': 'Nama Lengkap',
    'members.form.fullNamePlaceholder': 'contoh: Budi Santoso',
    'members.form.email': 'Email',
    'members.form.organization': 'Organisasi',
    'members.form.phone': 'Telepon',
    'members.form.job': 'Pekerjaan',
    'members.form.dob': 'Tanggal Lahir',
    'members.form.address': 'Alamat',
    'members.form.city': 'Kota',
    'members.form.notes': 'Catatan',
    'members.form.optional': 'Opsional',
    'members.table.name': 'Nama',
    'members.table.organization': 'Organisasi',
    'members.table.email': 'Email',
    'members.table.phone': 'Telepon',
    'members.table.contact': 'Kontak',
    'members.table.job': 'Pekerjaan',
    'members.table.city': 'Kota',
    'members.table.actions': 'Aksi',
    'members.excel.title': 'Format Import Excel',
    'members.excel.description': 'Silakan siapkan file Excel Anda dengan kolom-kolom berikut',
    'members.excel.requiredColumns': 'Kolom Wajib:',
    'members.excel.optionalColumns': 'Kolom Yang Diisi:',
    'members.excel.exampleFormat': 'Contoh Format:',
    'members.excel.note': 'Catatan:',
    'members.excel.noteText': 'Nama kolom tidak peka huruf besar/kecil. Anda bisa menggunakan "Name", "name", atau "NAME".',
    'members.excel.cancel': 'Batal',
    'members.excel.chooseFile': 'Pilih File Excel',
    'members.excel.importing': 'Mengimpor...',
    'members.excel.importExcel': 'Import Excel',
    'members.excel.nameRequired': 'Nama lengkap anggota (Wajib)',
    'members.search.noResults': 'Tidak ada anggota ditemukan',
    'members.search.noMatch': 'Tidak ada anggota yang cocok dengan pencarian Anda',
    'members.search.clearSearch': 'Hapus pencarian',
    'members.detail.title': 'Informasi Anggota',
    'members.detail.description': 'Informasi lengkap tentang',
    // My Certificates
    'myCertificates.title': 'Sertifikat Saya',
    'myCertificates.subtitle': 'Lihat dan kelola sertifikat Anda',
    'myCertificates.search': 'Cari sertifikat...',
    'myCertificates.noCertificates': 'Tidak ada sertifikat ditemukan',
    'myCertificates.download': 'Unduh',
    'myCertificates.verify': 'Verifikasi',
    
    // Certificate Generator
    'generator.title': 'Generator Sertifikat',
    'generator.subtitle': 'Buat dan sesuaikan sertifikat',
    'generator.template': 'Template',
    'generator.recipient': 'Informasi Penerima',
    'generator.preview': 'Pratinjau Sertifikat',
    'generator.generate': 'Generate Sertifikat',
    'generator.download': 'Unduh PDF',
    'generator.email': 'Kirim via Email',
    'generator.recipientName': 'Nama Penerima',
    'generator.recipientEmail': 'Email Penerima',
    'generator.courseName': 'Nama Kursus',
    'generator.completionDate': 'Tanggal Penyelesaian',
    'generator.certificateId': 'ID Sertifikat',
    'generator.organization': 'Organisasi',
    'generator.instructor': 'Instruktur',
    'generator.duration': 'Durasi',
    'generator.grade': 'Nilai',
    'generator.notes': 'Catatan',
    
    // Quick Generate Modal
    'quickGenerate.title': 'Generate Sertifikat',
    'quickGenerate.description': 'Generate sertifikat dengan memilih template dan sumber data',
    'quickGenerate.selectTemplate': 'Pilih Template',
    'quickGenerate.chooseTemplate': 'Pilih template...',
    'quickGenerate.loadingTemplates': 'Memuat template...',
    'quickGenerate.notConfigured': 'Belum Dikonfigurasi',
    'quickGenerate.dataSource': 'Sumber Data',
    'quickGenerate.selectMember': 'Pilih Anggota',
    'quickGenerate.selectMembers': 'Pilih Anggota',
    'quickGenerate.uploadExcel': 'Unggah Excel',
    'quickGenerate.loadingMembers': 'Memuat anggota...',
    'quickGenerate.noOrganization': 'Tidak Ada Organisasi',
    'quickGenerate.membersSelected': 'anggota terpilih',
    'quickGenerate.dateFormat': 'Format Tanggal',
    'quickGenerate.issueDate': 'Tanggal Terbit',
    'quickGenerate.expiredDate': 'Tanggal Kedaluwarsa',
    'quickGenerate.chooseExcelFile': 'Pilih File Excel',
    'quickGenerate.uploadExcelHint': 'Unggah file .xlsx atau .xls',
    'quickGenerate.rowsLoaded': 'baris dimuat',
    'quickGenerate.willGenerate': 'Ini akan menghasilkan',
    'quickGenerate.certificatesAtOnce': 'sertifikat sekaligus',
    'quickGenerate.cancel': 'Batal',
    'quickGenerate.generating': 'Membuat...',
    'quickGenerate.generate': 'Generate',
    'quickGenerate.selectTemplateError': 'Silakan pilih template',
    'quickGenerate.selectMemberError': 'Silakan pilih setidaknya satu anggota',
    'quickGenerate.uploadExcelError': 'Silakan unggah file Excel',
    'quickGenerate.generateError': 'Gagal membuat sertifikat',
    'quickGenerate.loadedRows': 'Dimuat',
    'quickGenerate.rowsFromExcel': 'baris dari Excel',
    'quickGenerate.parseExcelError': 'Gagal memproses file Excel',
    'quickGenerate.generatingCertificates': 'Membuat sertifikat...',
    'quickGenerate.successSingle': 'Sertifikat berhasil dibuat!',
    'quickGenerate.successMultiple': 'Berhasil membuat',
    'quickGenerate.certificatesGenerated': 'sertifikat!',
    
    // Navigation
    'nav.menu': 'Menu',
    
    // Error Messages - Search
    'error.search.notFound': 'Sertifikat tidak ditemukan. Silakan periksa nomor sertifikat atau link dan coba lagi.',
    'error.search.empty': 'Silakan masukkan nomor sertifikat atau nama untuk mencari',
    'error.search.failed': 'Pencarian gagal. Silakan coba lagi.',
    
    // Login Modal
    'login.welcomeBack': 'Selamat Datang Kembali',
    'login.signInMessage': 'Masuk ke akun Anda untuk melanjutkan',
    'login.emailAddress': 'Alamat Email',
    'login.password': 'Kata Sandi',
    'login.enterEmail': 'Masukkan email Anda',
    'login.enterPassword': 'Masukkan kata sandi Anda',
    'login.signIn': 'Masuk',
    'login.signingIn': 'Sedang masuk...',
    'login.orContinueWith': 'Atau lanjutkan dengan',
    
    // Auth Callback
    'auth.callback.finishingSignIn': 'Menyelesaikan masuk…',
    'auth.callback.signingYouIn': 'Memproses masuk Anda…',
    'auth.callback.finalisingSession': 'Menyelesaikan sesi…',
    'auth.callback.settingUpAccount': 'Menyiapkan akun Anda…',
    'auth.callback.almostDone': 'Hampir selesai…',
    'auth.callback.success': 'Login berhasil! Mengarahkan…',
    'auth.callback.authFailed': 'Autentikasi gagal. Mengarahkan ke beranda…',
    'auth.callback.authFailedShort': 'Autentikasi gagal. Mengarahkan…',
    'auth.callback.noSession': 'Sesi tidak ditemukan. Mengarahkan…',
    'auth.callback.errorOccurred': 'Terjadi kesalahan. Mengarahkan…',
    'auth.callback.takeMeHome': 'Bawa saya ke beranda',
    
    // Error Messages - Login
    'error.login.invalidEmail': 'Silakan masukkan alamat email yang valid.',
    'error.login.invalidPassword': 'Kata sandi Anda harus minimal 6 karakter.',
    'error.login.invalidCredentials': 'Email atau kata sandi salah.',
    
    // Search & Filter
    'search.filters': 'Filter',
    'search.category': 'Kategori',
    'search.allCategories': 'Semua Kategori',
    'search.dateRange': 'Rentang Tanggal',
    'search.startDate': 'Tanggal Mulai',
    'search.endDate': 'Tanggal Akhir',
    'search.clearFilters': 'Hapus Filter',
    'search.applyFilters': 'Terapkan Filter',
    'search.noResults': 'Tidak ada hasil yang cocok untuk',
    'search.noResultsGeneral': 'Tidak ada sertifikat ditemukan',
    'search.filteredBy': 'Difilter berdasarkan',
    'search.showingResults': 'Menampilkan hasil',
    'search.searchByName': 'Cari berdasarkan nama atau nomor sertifikat...',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      try {
        const saved = window.localStorage.getItem('ecert-language');
        if (saved === 'en' || saved === 'id') return saved;
      } catch {}
    }
    return 'en';
  });

  // removed unused hydrated state

  useEffect(() => {
    try {
      if (typeof window !== 'undefined') {
        window.localStorage.setItem('ecert-language', language);
      }
    } catch {}
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
